/*
 * Copyright © 2004 David Connet. All Rights Reserved.
 *
 * Permission to use, copy, modify and distribute this software and its
 * documentation for any purpose and without fee is hereby granted, provided
 * that the above copyright notice appear in all copies, that both the
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the names of David Connet, dcon Software,
 * AgilityBook, AgilityRecordBook or "Agility Record Book" not be used in
 * advertising or publicity pertaining to distribution of the software
 * without specific, written prior permission. David Connet makes no
 * representations about the suitability of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 *
 * DAVID CONNET DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
 * EVENT SHALL DAVID CONNET BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
 * USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 *
 * http://opensource.org
 * Open Source Historical Permission Notice and Disclaimer.
 */

/**
 * @file
 * @brief Translate resource.h/resource.hm for use in help.
 * @author David Connet
 *
 * This parses the auto-generated resource.hm in order to convert the hex
 * #defines into decimal so the hhc compiler will work with the text popups.
 * It also translates the IDD_ defines into contextid.h as id+HID_BASE_RESOURCE
 *
 * Revision History
 * @li 2004-06-05 DRC Changed usage to create contextid.h also.
 * @li 2004-05-20 DRC Created
 */

#if 0
>>>>>This is what resource.hm looks like:
// Microsoft Visual C++ generated Help ID include file.
// Used by AgilityBook.rc
//
#define HIDC_ABOUT_UPDATE               0x80c803ee    // IDD_ABOUTBOX

>>>>>This is what we need:
#define HIDC_ABOUT_UPDATE 2160591854
#endif

#include "../stdafx.h"
#include <afxpriv.h>
#include <iostream>
#include <fstream>
#include <string>
#include <tchar.h>

// Include these simply for re-compile and to cause the post-build event.
#include "../Win/resource.h"
#include "../Win/resource.hm"

using namespace std;

static string get_line(istream& file)
{
	char buffer[1000]; // We just "know" this is big enough. In fact, 80 would be good.

	file.getline(buffer, sizeof(buffer) - 1);
	int len = static_cast<int>(strlen(buffer));
	while (0 < len && !file.eof() && '\\' == buffer[len-1])
	{
		file.getline(&buffer[len-1], sizeof(buffer) - len - 1);
		len = static_cast<int>(strlen(buffer));
	}
	if (0 < len)
		return buffer;
	else
		return "";
}

static bool parse_define(string line, string& outDefine, unsigned long& outValue)
{
	outDefine.clear();
	outValue = 0;
	bool bParsed = false;
	if (0 < line.length())
	{
		string::size_type pos = line.find("//");
		if (0 <= pos)
			line = line.substr(0, pos);
		if (0 < line.length())
		{
			if (0 == line.find("#define"))
			{
				bParsed = true;
				pos = line.length() - 1;
				while (pos >= 0 && isspace(line[pos]))
					--pos;
				if (pos != line.length() - 1)
					line = line.substr(0, pos + 1);
				pos = line.find_first_of(" \t");
				while (isspace(line[pos]))
					++pos;
				line = line.substr(pos); // skip define and whitespace
				pos = line.find_first_of(" \t");
				outDefine = line.substr(0, pos); // macro
				while (isspace(line[pos]))
					++pos;
				line = line.substr(pos); // skip macro and whitespace
				if (0 == line.find("0x"))
					outValue = strtoul(line.c_str(), NULL, 16);
				else
					outValue = atol(line.c_str());
			}
		}
	}
	return bParsed;
}

int _tmain(int argc, _TCHAR* argv[])
{
	if (5 != argc)
	{
		cerr << "Usage: " << argv[0] << " resource.h resource.hm output/AgilityBook.h output/contextid.h" << endl;
		return 1;
	}
	string resourceH(argv[argc-4]);
	string resourceHM(argv[argc-3]);
	string agilitybookH(argv[argc-2]);
	string contextidH(argv[argc-1]);

	ifstream resHM(resourceHM.c_str());
	if (!resHM.is_open())
	{
		cerr << "Can't read " << resourceHM << endl;
		return 1;
	}
	ofstream arbH(agilitybookH.c_str());
	if (!arbH.is_open())
	{
		cerr << "Can't write " << agilitybookH << endl;
		return 1;
	}

	arbH << "// Autogenerated from " << resourceHM  << endl;
	while (!resHM.eof())
	{
		string line = get_line(resHM);
		string outDefine;
		unsigned long outValue;
		if (parse_define(line, outDefine, outValue))
		{
			arbH << "#define " << outDefine << " " << outValue << endl;
		}
	}
	resHM.close();
	arbH.close();

	ifstream resH(resourceH.c_str());
	if (!resH.is_open())
	{
		cerr << "Can't read " << resourceH << endl;
		return 1;
	}
	ofstream contextH(contextidH.c_str());
	if (!contextH.is_open())
	{
		cerr << "Can't write " << contextidH << endl;
		return 1;
	}

	contextH << "// Autogenerated from " << resourceH << endl;
	while (!resH.eof())
	{
		string line = get_line(resH);
		string outDefine;
		unsigned long outValue;
		if (parse_define(line, outDefine, outValue))
		{
			string defPrefix = outDefine.substr(0, 4);
			if (defPrefix == "IDD_" || defPrefix == "IDR_")
				contextH << "#define H" << outDefine << " " << HID_BASE_RESOURCE + outValue << endl;
		}
	}
	resH.close();
	contextH.close();

	return 0;
}
