//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgilityBook.rc
//
#define IDB_LOGO                        101
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_DTD_AGILITYRECORDBOOK       129
#define IDR_XML_DEFAULT_CONFIG          130
#define IDR_DOG                         132
#define IDR_TRIAL                       133
#define IDR_RUN                         134
#define IDR_POINTS                      135
#define IDR_CALENDAR                    136
#define IDR_TRAINING                    137
#define IDI_AGILITYBOOKDOC              150
#define IDI_CALENDAR_EMPTY              151
#define IDI_CALENDAR_TENTATIVE          152
#define IDI_CALENDAR_PLAN               153
#define IDI_CALENDAR_PLAN_TENTATIVE     154
#define IDI_CALENDAR_ENTERED            155
#define IDI_CALENDAR_ENTERED_TENTATIVE  156
#define IDI_CHECKED                     157
#define IDI_UNCHECKED                   158
#define IDI_CRCD                        159
#define IDI_TITLE                       160
#define IDI_TITLE2                      161
#define IDI_HIDDEN                      162
#define IDI_HEADER_UP                   163
#define IDI_HEADER_DOWN                 164
#define IDI_HELP                        165
#define IDD_ABOUTBOX                    200
#define IDD_NAME                        201
#define IDD_LIST_VIEWER                 202
#define IDD_LISTCTRL                    203
#define IDD_MESSAGE                     204
#define IDD_FIND                        205
#define IDD_CONFIGURE                   206
#define IDD_CONFIG_VENUE                207
#define IDD_CONFIG_EVENT                208
#define IDD_CONFIG_OTHERPOINTS          209
#define IDD_CONFIG_TITLE                210
#define IDD_CONFIG_UPDATE               211
#define IDD_CALENDAR                    212
#define IDD_TRAINING                    213
#define IDD_JUDGE_INFO                  214
#define IDD_DOG_PICKER                  215
#define IDD_DOG_POINTS                  216
#define IDD_DOG_PROP                    217
#define IDD_DOG_TITLES                  218
#define IDD_DOG_NUMBERS                 219
#define IDD_REG_NUM                     220
#define IDD_TITLE                       221
#define IDD_EXISTING_POINTS             222
#define IDD_TRIAL                       223
#define IDD_CLUB                        224
#define IDD_RUN_SCORE                   225
#define IDD_RUN_COMMENTS                226
#define IDD_RUN_REFERENCE               227
#define IDD_RUN_CRCD                    228
#define IDD_RUN_LINK                    229
#define IDD_REF_RUN                     230
#define IDD_PARTNER                     231
#define IDD_OTHER_POINT                 232
#define IDD_FAULT                       233
#define IDD_CONFIG_TITLE_POINTS         234
#define IDD_CRCD_VIEWER                 235
#define IDD_SELECT_URL                  236
#define IDD_VIEW_OPTIONS_CALENDAR       237
#define IDD_VIEW_OPTIONS_FILTER         238
#define IDD_VIEW_OPTIONS_FONTS          239
#define IDD_VIEW_OPTIONS_TRAINING       240
#define IDD_VIEW_OPTIONS_PROGRAM        241
#define IDD_REORDER                     242
#define IDD_WIZARD_START                243
#define IDD_WIZARD_IMPORT               244
#define IDD_WIZARD_EXPORT               245
#define IDD_ASSIGN_COLUMNS              246
#define IDD_FIND_LINKS                  247
#define IDD_MESSAGE_BOX                 248
#define IDD_PROGRESS_DLG                249
#define IDC_ABOUT_TEXT                  1000
#define IDC_ABOUT_TEXT2                 1001
#define IDC_ABOUT_LINK1                 1002
#define IDC_ABOUT_LINK2                 1003
#define IDC_ABOUT_LINK3                 1004
#define IDC_ABOUT_LINK4                 1005
#define IDC_ABOUT_UPDATE                1006
#define IDC_ABOUT_LINK5                 1007
#define IDC_NAME                        1010
#define IDC_LIST_VIEWER                 1020
#define IDC_LIST_COPY                   1021
#define IDC_LIST                        1030
#define IDC_LIST_NEW                    1031
#define IDC_LIST_EDIT                   1032
#define IDC_LIST_DELETE                 1033
#define IDC_LIST_MOVE_UP                1034
#define IDC_LIST_MOVE_DOWN              1035
#define IDC_LIST_TRIAL                  1036
#define IDC_MESSAGE                     1040
#define IDC_FIND_NAME                   1050
#define IDC_FIND_CASE                   1051
#define IDC_FIND_ALL                    1052
#define IDC_FIND_VISIBLE                1053
#define IDC_FIND_UP                     1054
#define IDC_FIND_DOWN                   1055
#define IDC_CONFIG_VENUES               1060
#define IDC_CONFIG_NEW                  1061
#define IDC_CONFIG_EDIT                 1062
#define IDC_CONFIG_DELETE               1063
#define IDC_CONFIG_COPY                 1064
#define IDC_CONFIG_COMMENTS             1065
#define IDC_CONFIG_FAULTS               1066
#define IDC_CONFIG_OTHERPOINTS          1067
#define IDC_CONFIG_UPDATE               1068
#define IDC_CONFIG_VENUE                1070
#define IDC_CONFIG_VENUE_DESC           1071
#define IDC_CONFIG_VENUE_DIVISION       1072
#define IDC_CONFIG_VENUE_LEVEL          1073
#define IDC_CONFIG_VENUE_NEW            1074
#define IDC_CONFIG_VENUE_DELETE         1075
#define IDC_CONFIG_VENUE_EDIT           1076
#define IDC_CONFIG_VENUE_COPY           1077
#define IDC_CONFIG_VENUE_MOVE_UP        1078
#define IDC_CONFIG_VENUE_MOVE_DOWN      1079
#define IDC_CONFIG_VENUE_COMMENTS       1080
#define IDC_CONFIG_VENUE_EVENT          1081
#define IDC_CONFIG_VENUE_TITLES         1082
#define IDC_CONFIG_VENUE_LONGNAME       1083
#define IDC_CONFIG_EVENT                1090
#define IDC_CONFIG_EVENT_TABLE          1091
#define IDC_CONFIG_EVENT_PARTNER        1092
#define IDC_CONFIG_EVENT_TIME_FAULTS_UNDER 1093
#define IDC_CONFIG_EVENT_TIME_FAULTS_OVER 1094
#define IDC_CONFIG_EVENT_DESC           1097
#define IDC_CONFIG_EVENT_METHODS        1098
#define IDC_CONFIG_EVENT_UNUSED         1099
#define IDC_CONFIG_EVENT_NEW            1100
#define IDC_CONFIG_EVENT_DELETE         1101
#define IDC_CONFIG_EVENT_COPY           1102
#define IDC_CONFIG_EVENT_MOVE_UP        1103
#define IDC_CONFIG_EVENT_MOVE_DOWN      1104
#define IDC_CONFIG_EVENT_DATE_VALID_FROM 1105
#define IDC_CONFIG_EVENT_DATE_START     1106
#define IDC_CONFIG_EVENT_DATE_VALID_TO  1107
#define IDC_CONFIG_EVENT_DATE_END       1108
#define IDC_CONFIG_EVENT_DIVISION       1109
#define IDC_CONFIG_EVENT_LEVEL          1110
#define IDC_CONFIG_EVENT_TYPE           1111
#define IDC_CONFIG_EVENT_DROP_FRACTIONS 1112
#define IDC_CONFIG_EVENT_OPENING_PTS_TEXT 1113
#define IDC_CONFIG_EVENT_OPENING_PTS    1114
#define IDC_CONFIG_EVENT_CLOSING_PTS_TEXT 1115
#define IDC_CONFIG_EVENT_CLOSING_PTS    1116
#define IDC_CONFIG_EVENT_SUPERQ         1117
#define IDC_CONFIG_EVENT_SPEED          1118
#define IDC_CONFIG_EVENT_DOUBLEQ        1119
#define IDC_CONFIG_EVENT_NOTES          1120
#define IDC_CONFIG_EVENT_POINTS         1121
#define IDC_CONFIG_EVENT_POINTS_NEW     1122
#define IDC_CONFIG_EVENT_POINTS_EDIT    1123
#define IDC_CONFIG_EVENT_POINTS_DELETE  1124
#define IDC_CONFIG_EVENT_TF_MULTIPLY_TEXT 1125
#define IDC_CONFIG_EVENT_TF_MULTIPLY    1126
#define IDC_CONFIG_EVENT_HAS_SUBNAMES   1127
#define IDC_CONFIG_EVENT_SUBNAMES       1128
#define IDC_CONFIG_EVENT_SUBNAMES_NEW   1129
#define IDC_CONFIG_EVENT_SUBNAMES_DELETE 1130
#define IDC_CONFIG_OTHER_NAME           1130
#define IDC_CONFIG_OTHER_TALLY          1131
#define IDC_CONFIG_OTHER_DESC           1132
#define IDC_CONFIG_TITLE_NAME           1140
#define IDC_CONFIG_TITLE_LONG_NAME      1141
#define IDC_CONFIG_TITLE_DESC           1142
#define IDC_CONFIG_TITLE_ALLOW_MULTIPLE 1143
#define IDC_CONFIG_TITLE_MULTIPLE       1144
#define IDC_CONFIG_UPDATE_DEFAULT       1150
#define IDC_CONFIG_UPDATE_EXISTING      1151
#define IDC_CONFIG_UPDATE_NAME          1152
#define IDC_CONFIG_UPDATE_FILENAME      1153
#define IDC_CAL_DATE_START              1160
#define IDC_CAL_DATE_END                1161
#define IDC_CAL_TENTATIVE               1162
#define IDC_CAL_ENTER_NOT               1163
#define IDC_CAL_ENTER_PLANNING          1164
#define IDC_CAL_ENTER_ENTERED           1165
#define IDC_CAL_LOCATION                1166
#define IDC_CAL_CLUB                    1167
#define IDC_CAL_VENUE                   1168
#define IDC_CAL_DATE_OPENS              1169
#define IDC_CAL_DATE_OPENS_UNKNOWN      1170
#define IDC_CAL_DATE_CLOSES             1171
#define IDC_CAL_DATE_CLOSES_UNKNOWN     1172
#define IDC_CAL_NOTES                   1173
#define IDC_CAL_LOCATION_NOTE           1174
#define IDC_CAL_CLUB_NOTE               1175
#define IDC_TRAINING_DATE               1180
#define IDC_TRAINING_NAME               1181
#define IDC_TRAINING_NOTES              1182
#define IDC_TRAINING_SUBNAME            1183
#define IDC_JUDGE                       1190
#define IDC_JUDGE_NEW                   1191
#define IDC_JUDGE_DELETE                1192
#define IDC_JUDGE_COMMENTS              1193
#define IDC_PICK_NAME                   1200
#define IDC_DOGPTS_POINTS               1210
#define IDC_DOGPTS_NEW                  1211
#define IDC_DOGPTS_EDIT                 1212
#define IDC_DOGPTS_DELETE               1213
#define IDC_DOG_CALLNAME                1220
#define IDC_DOG_BREED                   1221
#define IDC_DOG_REG_NAME                1222
#define IDC_DOG_AGE_TEXT                1223
#define IDC_DOG_DOB                     1224
#define IDC_DOG_IS_DECEASED             1225
#define IDC_DOG_DECEASED                1227
#define IDC_DOG_NOTES                   1228
#define IDC_DOG_TITLE_TITLES            1230
#define IDC_DOG_TITLE_NEW               1231
#define IDC_DOG_TITLE_EDIT              1232
#define IDC_DOG_TITLE_DELETE            1233
#define IDC_DOG_TITLE_HIDDEN            1234
#define IDC_DOGNUM_REG_NUMS             1240
#define IDC_DOGNUM_NEW                  1241
#define IDC_DOGNUM_EDIT                 1242
#define IDC_DOGNUM_DELETE               1243
#define IDC_REGNUM_NOTE                 1250
#define IDC_REGNUM_VENUES               1251
#define IDC_REGNUM_REG_NUM              1252
#define IDC_REGNUM_HEIGHT               1253
#define IDC_REGNUM_RECEIVED             1254
#define IDC_TITLE_EARNED                1260
#define IDC_TITLE_DATE                  1261
#define IDC_TITLE_HIDDEN                1262
#define IDC_TITLE_VENUES                1263
#define IDC_TITLE_TITLES                1264
#define IDC_TITLE_RECEIVED              1265
#define IDC_TITLE_DESC                  1266
#define IDC_EXISTING_DATE               1270
#define IDC_EXISTING_TYPE               1271
#define IDC_EXISTING_POINTS             1272
#define IDC_EXISTING_OTHERPOINTS        1273
#define IDC_EXISTING_VENUES             1274
#define IDC_EXISTING_DIVISION           1275
#define IDC_EXISTING_LEVEL              1276
#define IDC_EXISTING_EVENT              1277
#define IDC_EXISTING_COMMENTS           1278
#define IDC_EXISTING_SUBNAME            1279
#define IDC_TRIAL_LOCATION              1280
#define IDC_TRIAL_NOTES                 1281
#define IDC_TRIAL_CLUB_NEW              1282
#define IDC_TRIAL_CLUB_EDIT             1283
#define IDC_TRIAL_CLUB_DELETE           1284
#define IDC_TRIAL_CLUBS                 1285
#define IDC_TRIAL_VERIFIED              1286
#define IDC_TRIAL_LOCATION_INFO         1287
#define IDC_TRIAL_CLUB_INFO             1288
#define IDC_CLUB_CLUBS                  1290
#define IDC_CLUB_VENUES                 1291
#define IDC_RUNSCORE_DATE               1300
#define IDC_RUNSCORE_VENUE              1301
#define IDC_RUNSCORE_CLUB               1302
#define IDC_RUNSCORE_LOCATION           1303
#define IDC_RUNSCORE_DIVISION           1304
#define IDC_RUNSCORE_LEVEL              1305
#define IDC_RUNSCORE_EVENT              1306
#define IDC_RUNSCORE_DESC               1307
#define IDC_RUNSCORE_HEIGHT             1308
#define IDC_RUNSCORE_JUDGE              1309
#define IDC_RUNSCORE_HANDLER            1310
#define IDC_RUNSCORE_CONDITIONS         1311
#define IDC_RUNSCORE_PARTNERS_EDIT      1312
#define IDC_RUNSCORE_PARTNER            1313
#define IDC_RUNSCORE_FAULTS_TEXT        1314
#define IDC_RUNSCORE_FAULTS             1315
#define IDC_RUNSCORE_TIME_TEXT          1316
#define IDC_RUNSCORE_TIME               1317
#define IDC_RUNSCORE_TABLE              1318
#define IDC_RUNSCORE_OPENING_PTS_TEXT   1319
#define IDC_RUNSCORE_OPENING_PTS        1320
#define IDC_RUNSCORE_CLOSING_PTS_TEXT   1321
#define IDC_RUNSCORE_CLOSING_PTS        1322
#define IDC_RUNSCORE_OPEN_PTS_TEXT      1323
#define IDC_RUNSCORE_OPEN_PTS           1324
#define IDC_RUNSCORE_CLOSE_PTS_TEXT     1325
#define IDC_RUNSCORE_CLOSE_PTS          1326
#define IDC_RUNSCORE_YARDS_TEXT         1327
#define IDC_RUNSCORE_YARDS              1328
#define IDC_RUNSCORE_YPS_TEXT           1329
#define IDC_RUNSCORE_YPS                1330
#define IDC_RUNSCORE_SCT_TEXT           1331
#define IDC_RUNSCORE_SCT                1332
#define IDC_RUNSCORE_SCT2_TEXT          1333
#define IDC_RUNSCORE_SCT2               1334
#define IDC_RUNSCORE_TOTAL_FAULTS_TEXT  1335
#define IDC_RUNSCORE_TOTAL_FAULTS       1336
#define IDC_RUNSCORE_PLACE              1337
#define IDC_RUNSCORE_IN_CLASS           1338
#define IDC_RUNSCORE_DOGS_QD            1339
#define IDC_RUNSCORE_Q                  1340
#define IDC_RUNSCORE_SCORE              1341
#define IDC_RUNSCORE_DOUBLE_Q           1342
#define IDC_RUNSCORE_SPEEDPTS_TEXT      1343
#define IDC_RUNSCORE_SPEEDPTS           1344
#define IDC_RUNSCORE_TITLE_POINTS_TEXT  1345
#define IDC_RUNSCORE_TITLE_POINTS       1346
#define IDC_RUNSCORE_OTHERPOINTS        1347
#define IDC_RUNSCORE_SUBNAME_TEXT       1348
#define IDC_RUNSCORE_SUBNAME            1349
#define IDC_RUNCOMMENT_COMMENTS         1350
#define IDC_RUNCOMMENT_FAULTS_LIST      1351
#define IDC_RUNCOMMENT_COMMENTS_FAULTS  1352
#define IDC_RUNREF_REF_RUNS             1360
#define IDC_RUNREF_NEW                  1361
#define IDC_RUNREF_EDIT                 1362
#define IDC_RUNREF_DELETE               1363
#define IDC_RUNCRCD_EDIT                1370
#define IDC_RUNCRCD_VIEW                1371
#define IDC_RUNCRCD_COPY                1372
#define IDC_RUNCRCD_CRCD                1373
#define IDC_RUNCRCD_DESC                1374
#define IDC_RUNLINK_LIST                1380
#define IDC_RUNLINK_NEW                 1381
#define IDC_RUNLINK_EDIT                1382
#define IDC_RUNLINK_DELETE              1383
#define IDC_RUNLINK_OPEN                1384
#define IDC_REFRUN_PLACE                1390
#define IDC_REFRUN_Q                    1391
#define IDC_REFRUN_HEIGHT               1392
#define IDC_REFRUN_TIME                 1393
#define IDC_REFRUN_NAME                 1394
#define IDC_REFRUN_BREED                1395
#define IDC_REFRUN_NOTES                1396
#define IDC_REFRUN_POINTS               1397
#define IDC_PARTNER_NAME                1400
#define IDC_PARTNER_CALLNAME            1401
#define IDC_PARTNER_REG_NUM             1402
#define IDC_OTHER_OTHERPOINTS           1410
#define IDC_OTHER_DESC                  1411
#define IDC_OTHER_POINTS                1412
#define IDC_FAULTS                      1420
#define IDC_CONFIG_TITLEPTS_FAULTS      1430
#define IDC_CONFIG_TITLEPTS_POINTS      1431
#define IDC_CONFIG_TITLEPTS_TITLE_POINTS 1432
#define IDC_VIEWER_CRCD                 1440
#define IDC_SELECTURL_NAME              1450
#define IDC_SELECTURL_FILENAME          1451
#define IDC_OPTIONS_CAL_COLOR_OPEN      1456
#define IDC_OPTIONS_CAL_COLOR_OPEN_SET  1457
#define IDC_OPTIONS_CAL_COLOR_CLOSE     1458
#define IDC_OPTIONS_CAL_COLOR_CLOSE_SET 1459
#define IDC_OPTIONS_CAL_DAY_OF_WEEK     1460
#define IDC_OPTIONS_CAL_AUTO_DELETE     1461
#define IDC_OPTIONS_CAL_HIDE_OLD        1462
#define IDC_OPTIONS_CAL_OLD_ENTRY_DAYS  1463
#define IDC_OPTIONS_CAL_HIDE_OVERLAP    1464
#define IDC_OPTIONS_CAL_SIZE_X          1465
#define IDC_OPTIONS_CAL_SIZE_Y          1466
#define IDC_OPTIONS_CAL_NORMAL          1467
#define IDC_OPTIONS_CAL_OPENING         1468
#define IDC_OPTIONS_CAL_CLOSING         1469
#define IDC_OPTIONS_FILTER_VENUES_ALL   1470
#define IDC_OPTIONS_FILTER_VENUES_SELECTED 1471
#define IDC_OPTIONS_FILTER_VENUES       1472
#define IDC_OPTIONS_FILTER_DATES_ALL    1473
#define IDC_OPTIONS_FILTER_DATES_RANGE  1474
#define IDC_OPTIONS_FILTER_DATE_START_CHECK 1475
#define IDC_OPTIONS_FILTER_DATE_START   1476
#define IDC_OPTIONS_FILTER_DATE_END_CHECK 1477
#define IDC_OPTIONS_FILTER_DATE_END     1478
#define IDC_OPTIONS_FILTER_RUNS_ALL     1479
#define IDC_OPTIONS_FILTER_RUNS_Q       1480
#define IDC_OPTIONS_FILTER_RUNS_NON_Q   1481
#define IDC_OPTIONS_FONT_CAL_PRINT_DATE_TEXT 1490
#define IDC_OPTIONS_FONT_CAL_PRINT_DATE 1491
#define IDC_OPTIONS_FONT_CAL_PRINT_TEXT_TEXT 1492
#define IDC_OPTIONS_FONT_CAL_PRINT_TEXT 1493
#define IDC_OPTIONS_FONT_CAL_VIEW_DATE_TEXT 1494
#define IDC_OPTIONS_FONT_CAL_VIEW_DATE  1495
#define IDC_OPTIONS_FONT_CAL_VIEW_TEXT_TEXT 1496
#define IDC_OPTIONS_FONT_CAL_VIEW_TEXT  1497
#define IDC_OPTIONS_FONT_GENERAL_PRINT_TEXT 1498
#define IDC_OPTIONS_FONT_GENERAL_PRINT  1499
#define IDC_OPTIONS_TRAINING_VENUES_ALL 1510
#define IDC_OPTIONS_TRAINING_VENUES_SELECTED 1511
#define IDC_OPTIONS_TRAINING_VENUES     1512
#define IDC_OPTIONS_TRAINING_DATES_ALL  1513
#define IDC_OPTIONS_TRAINING_DATES_RANGE 1514
#define IDC_OPTIONS_TRAINING_DATE_START_CHECK 1515
#define IDC_OPTIONS_TRAINING_DATE_START 1516
#define IDC_OPTIONS_TRAINING_DATE_END_CHECK 1517
#define IDC_OPTIONS_TRAINING_DATE_END   1518
#define IDC_OPTIONS_PGM_AUTO_CHECK      1520
#define IDC_OPTIONS_PGM_EDIT            1521
#define IDC_OPTIONS_PGM_AUTOSHOW        1522
#define IDC_OPTIONS_PGM_FILENAME        1523
#define IDC_OPTIONS_PGM_BROWSE          1524
#define IDC_OPTIONS_PGM_SHOW_SPLASH     1525
#define IDC_REORDER_LIST                1530
#define IDC_REORDER_MOVE_UP             1531
#define IDC_REORDER_MOVE_DOWN           1532
#define IDC_WIZARD_START_EXCEL          1540
#define IDC_WIZARD_START_SPREADSHEET    1541
#define IDC_WIZARD_START_ARB            1542
#define IDC_WIZARD_START_LIST           1543
#define IDC_WIZARD_START_DESCRIPTION    1544
#define IDC_WIZARD_IMPORT_ROW           1550
#define IDC_WIZARD_IMPORT_ROW_SPIN      1551
#define IDC_WIZARD_IMPORT_DELIM_GROUP   1552
#define IDC_WIZARD_IMPORT_DELIM_TAB     1553
#define IDC_WIZARD_IMPORT_DELIM_SPACE   1554
#define IDC_WIZARD_IMPORT_DELIM_COLON   1555
#define IDC_WIZARD_IMPORT_DELIM_SEMI    1556
#define IDC_WIZARD_IMPORT_DELIM_COMMA   1557
#define IDC_WIZARD_IMPORT_DELIM_OTHER   1558
#define IDC_WIZARD_IMPORT_DELIM         1559
#define IDC_WIZARD_IMPORT_DATE          1560
#define IDC_WIZARD_IMPORT_ASSIGN        1561
#define IDC_WIZARD_IMPORT_FILE          1562
#define IDC_WIZARD_IMPORT_PREVIEW_FILE  1563
#define IDC_WIZARD_IMPORT_PREVIEW       1564
#define IDC_WIZARD_EXPORT_DELIM_GROUP   1570
#define IDC_WIZARD_EXPORT_DELIM_TAB     1571
#define IDC_WIZARD_EXPORT_DELIM_SPACE   1572
#define IDC_WIZARD_EXPORT_DELIM_COLON   1573
#define IDC_WIZARD_EXPORT_DELIM_SEMI    1574
#define IDC_WIZARD_EXPORT_DELIM_COMMA   1575
#define IDC_WIZARD_EXPORT_DELIM_OTHER   1576
#define IDC_WIZARD_EXPORT_DELIM         1577
#define IDC_WIZARD_EXPORT_DATE          1578
#define IDC_WIZARD_EXPORT_ASSIGN        1579
#define IDC_WIZARD_EXPORT_PREVIEW       1580
#define IDC_ASSIGN_TYPE                 1590
#define IDC_ASSIGN_AVAILABLE            1591
#define IDC_ASSIGN_ADD                  1592
#define IDC_ASSIGN_DELETE               1593
#define IDC_ASSIGN_MOVE_UP              1594
#define IDC_ASSIGN_MOVE_DOWN            1595
#define IDC_ASSIGN_COLUMNS              1596
#define IDC_FINDLINKS_LIST              1600
#define IDC_FINDLINKS_COPY              1601
#define IDC_FINDLINKS_EDIT              1602
#define IDC_FINDLINKS_OPEN              1603
#define IDC_MESSAGE_BOX_ICON            1610
#define IDC_MESSAGE_BOX_TEXT            1611
#define IDC_MESSAGE_BOX_BUTTON1         1612
#define IDC_MESSAGE_BOX_BUTTON2         1613
#define IDC_MESSAGE_BOX_BUTTON3         1614
#define IDC_MESSAGE_BOX_DETAILS         1615
#define IDC_PROGRESS_MESSAGE            1620
#define IDC_PROGRESS_BAR1               1621
#define IDC_PROGRESS_BAR2               1622
#define IDS_COL_BREED                   4000
#define IDS_COL_CLOSES                  4001
#define IDS_COL_CLUB                    4002
#define IDS_COL_DATE                    4003
#define IDS_COL_DIVISION                4004
#define IDS_COL_DOG                     4005
#define IDS_COL_END_DATE                4006
#define IDS_COL_EVENT                   4007
#define IDS_COL_FAULT                   4008
#define IDS_COL_HANDLER                 4009
#define IDS_COL_IN_CLASS                4010
#define IDS_COL_JUDGE                   4011
#define IDS_COL_LEVEL                   4012
#define IDS_COL_LOCATION                4013
#define IDS_COL_NAME                    4014
#define IDS_COL_NOTE                    4015
#define IDS_COL_NOTES                   4016
#define IDS_COL_NUMBER                  4017
#define IDS_COL_OPENS                   4018
#define IDS_COL_PLACE                   4019
#define IDS_COL_POINTS                  4020
#define IDS_COL_PTS                     4021
#define IDS_COL_Q                       4022
#define IDS_COL_Q_D                     4023
#define IDS_COL_RECEIVED                4024
#define IDS_COL_SCORE                   4025
#define IDS_COL_START_DATE              4026
#define IDS_COL_TIME                    4027
#define IDS_COL_VENUE                   4028
#define IDS_COL_HEIGHT                  4029
#define IDS_COL_REG_NAME                4030
#define IDS_COL_CALLNAME                4031
#define IDS_COL_TRIALNOTES              4032
#define IDS_COL_CONDITIONS              4033
#define IDS_COL_COURSEFAULTS            4034
#define IDS_COL_YARDS                   4035
#define IDS_COL_YPS                     4036
#define IDS_COL_SCT                     4037
#define IDS_COL_TOTAL_FAULTS            4038
#define IDS_COL_REQ_OPENING             4039
#define IDS_COL_REQ_CLOSING             4040
#define IDS_COL_OPENING                 4041
#define IDS_COL_CLOSING                 4042
#define IDS_COL_REQ_POINTS              4043
#define IDS_COL_TITLE_PTS               4044
#define IDS_COL_COMMENTS                4045
#define IDS_COL_FAULTS                  4046
#define IDS_COL_TENTATIVE               4047
#define IDS_COL_ENTERED                 4048
#define IDS_COL_DOB                     4049
#define IDS_COL_AGE                     4050
#define IDS_COL_TYPE                    4051
#define IDS_COL_TITLE                   4052
#define IDS_COL_TRIAL                   4053
#define IDS_COL_SUBNAME                 4054
#define IDS_COL_VERIFIED                4055
#define IDS_COL_SPEED                   4056
#define IDS_BUTTON_OK                   4080
#define IDS_BUTTON_CANCEL               4081
#define IDS_BUTTON_YES                  4082
#define IDS_BUTTON_NO                   4083
#define IDS_BUTTON_ABORT                4084
#define IDS_BUTTON_IGNORE               4085
#define IDS_BUTTON_RETRY                4086
#define IDS_RUNS                        5000
#define IDS_POINTS                      5001
#define IDS_CALENDAR                    5002
#define IDS_TRAINING                    5003
#define IDS_PARTNERS                    5010
#define IDS_VENUES                      5011
#define IDS_VENUE_NAME                  5012
#define IDS_FAULT_TYPES                 5013
#define IDS_FAULT_TYPE_NAME             5014
#define IDS_OTHERPOINTS                 5015
#define IDS_OTHERPOINTS_NAME            5016
#define IDS_DIVISIONS                   5017
#define IDS_DIVISION_NAME               5018
#define IDS_TITLES                      5019
#define IDS_LEVELS                      5021
#define IDS_LEVEL_NAME                  5022
#define IDS_SUBLEVEL_NAME               5023
#define IDS_EVENTS                      5024
#define IDS_EVENT_NAME                  5025
#define IDS_SCORING                     5026
#define IDS_Q                           5027
#define IDS_SQ                          5028
#define IDS_SUPER_Q                     5029
#define IDS_QQ                          5030
#define IDS_DOUBLE_Q                    5031
#define IDS_SPEEDPTS                    5032
#define IDS_EXISTING_POINTS             5033
#define IDS_ARE_YOU_SURE                5078
#define IDS_ABOUT_VERSION               5079
#define IDS_ABOUT_TEXT                  5080
#define IDS_HELP_UPDATE                 5081
#define IDS_ABOUT_LINK_YAHOO            5082
#define IDS_ABOUT_LINK_EMAILHELP        5083
#define IDS_ABOUT_LINK_ARB              5084
#define IDS_ABOUT_LINK_SOURCEFORGE      5085
#define IDS_UPDATE_NEWER_VERSION        5086
#define IDS_UPDATE_CURRENT              5087
#define IDS_UPDATE_UNKNOWN              5088
#define IDS_DELETE_EVENT_SCORING_INFO   5089
#define IDS_DELETE_EVENT_SCORING        5090
#define IDS_NEW                         5091
#define IDS_CONFIGURE                   5092
#define IDS_SCORING_NAME                5093
#define IDS_DELETE_VENUE                5094
#define IDS_DELETE_OTHERPOINTS          5095
#define IDS_DELETE_DIVISION             5096
#define IDS_DELETE_LEVEL                5097
#define IDS_DELETE_TITLE                5098
#define IDS_DELETE_EVENT                5099
#define IDS_DELETE_ALL                  5100
#define IDS_DELETE_ALL_OTHERPOINTS      5101
#define IDS_DELETE_ALL_TITLES           5102
#define IDS_NAME_IN_USE                 5103
#define IDS_ALL                         5104
#define IDS_TITLEPTS_EXISTS             5105
#define IDS_MIN_RESOLUTION              5106
#define IDS_CANNOT_OPEN                 5107
#define IDS_VIEWING_OPTIONS             5108
#define IDS_RUN_PROPERTIES              5109
#define IDS_CONFIG_DELETE_RUNS          5110
#define IDS_SELECT_DIVISION             5111
#define IDS_SELECT_LEVEL                5112
#define IDS_SELECT_EVENT                5113
#define IDS_ABOUT_LINK_YAHOO_FILES      5114
#define IDS_SELECT_JUDGE                5115
#define IDS_SELECT_Q                    5116
#define IDS_BAD_EVENT                   5117
#define IDS_BAD_SCORINGMETHOD           5118
#define IDS_SCORING_REQUIRED_POINTS     5119
#define IDS_SCORING_POINTS              5120
#define IDS_NUM_EVENTS                  5121
#define IDS_NUM_RUNS_QS                 5122
#define IDS_AUTODELETE_CAL              5123
#define IDS_CREATETRIAL_FAILED          5124
#define IDS_NEED_CLUB                   5125
#define IDS_VENUE_CONFIG_MISSING        5126
#define IDS_DELETE_DOG_DATA             5127
#define IDS_DELETE_TRIAL_DATA           5128
#define IDS_DELETE_EVENT_DATA           5129
#define IDS_COPYOF                      5130
#define IDS_CHANGEDIV_ISSUES            5131
#define IDS_CHANGELEVEL_ISSUES          5132
#define IDS_CHANGESUBLEVEL_ISSUES       5133
#define IDS_NOCONFIGDATA_FOUND          5134
#define IDS_UNKNOWN_DOCUMENT_VERSION    5135
#define IDS_OTHERPTS_ALL                5136
#define IDS_OTHERPTS_EVENT              5137
#define IDS_OTHERPTS_LEVEL              5138
#define IDS_OTHERPTS_EVENT_LEVEL        5139
#define IDS_CONFIG_NO_UPDATE            5140
#define IDS_XERCES_ERROR                5141
#define IDS_POINTS_RUNS_JUDGES          5142
#define IDS_POINTS_PARTNERS             5143
#define IDS_POINTS_QS                   5144
#define IDS_POINTS_CLEAN                5145
#define IDS_POINTS_JUDGES               5146
#define IDS_POINTS_SQS                  5147
#define IDS_POINTS_SPEED_SUBTOTAL       5148
#define IDS_POINTS_QQS                  5149
#define IDS_POINTS_SPEED                5150
#define IDS_CONFIG_TITLEPTS             5151
#define IDS_FILEEXT_DEF_ARB             5152
#define IDS_FILEEXT_FNAME_ARB           5153
#define IDS_FILEEXT_FILTER_ARB          5154
#define IDS_CREATERUN_FAILED            5155
#define IDS_CREATETRIAL_FILTERED        5156
#define IDS_CREATERUN_FILTERED          5157
#define IDS_NUM_TRAINING                5158
#define IDS_FILEEXT_DEF_DTD             5159
#define IDS_FILEEXT_FNAME_DTD           5160
#define IDS_FILEEXT_FILTER_DTD          5161
#define IDS_FILEEXT_DEF_XML             5162
#define IDS_FILEEXT_FNAME_XML           5163
#define IDS_FILEEXT_FILTER_XML          5164
#define IDS_ADDED_CAL_ITEMS             5165
#define IDS_FILEEXT_FILTER_TXT          5166
#define IDS_FILE_PREVIEW                5167
#define IDS_BLANK_COLUMN                5168
#define IDS_ADDED_TRAINING_ITEMS        5169
#define IDS_LIFETIME_POINTS             5170
#define IDS_CREATEDOG_FAILED            5171
#define IDS_INDICATOR_BLANK             5172
#define IDS_ADDED_DOGS                  5173
#define IDS_ADDED_REGNUMS               5174
#define IDS_ADDED_EXISTINGPTS           5175
#define IDS_ADDED_TITLES                5176
#define IDS_ADDED_TRIALS                5177
#define IDS_ADDED_JUDGES                5178
#define IDS_FILEEXT_FILTER_XLS          5179
#define IDS_ADDED_CLUBS                 5180
#define IDS_ADDED_LOCATIONS             5181
#define IDS_INFO_CLUB                   5182
#define IDS_INFO_JUDGE                  5183
#define IDS_INFO_LOCATION               5184
#define ID_FILE_EXPORT_WIZARD           32772
#define ID_FILE_LINKED                  32774
#define ID_EDIT_FIND_NEXT               32780
#define ID_EDIT_FIND_PREVIOUS           32781
#define ID_EDIT_CONFIGURATION           32782
#define ID_EDIT_DUPLICATE               32784
#define ID_AGILITY_NEW_CALENDAR         32790
#define ID_AGILITY_NEW_TRAINING         32791
#define ID_AGILITY_NEW_DOG              32792
#define ID_AGILITY_NEW_TITLE            32793
#define ID_AGILITY_NEW_TRIAL            32794
#define ID_AGILITY_NEW_RUN              32795
#define ID_AGILITY_EDIT_CALENDAR        32796
#define ID_AGILITY_EDIT_TRAINING        32797
#define ID_AGILITY_EDIT_DOG             32798
#define ID_AGILITY_EDIT_TITLE           32799
#define ID_AGILITY_EDIT_TRIAL           32800
#define ID_AGILITY_EDIT_RUN             32801
#define ID_AGILITY_DELETE_CALENDAR      32802
#define ID_AGILITY_DELETE_TRAINING      32803
#define ID_AGILITY_DELETE_DOG           32804
#define ID_AGILITY_DELETE_TITLE         32805
#define ID_AGILITY_DELETE_TRIAL         32806
#define ID_AGILITY_DELETE_RUN           32807
#define ID_AGILITY_CREATEENTRY_CALENDAR 32808
#define ID_NOTES_CLUBS                  32810
#define ID_NOTES_JUDGES                 32811
#define ID_NOTES_LOCATIONS              32812
#define ID_NOTES_SEARCH                 32813
#define ID_VIEW_OPTIONS                 32820
#define ID_VIEW_CUSTOMIZE               32821
#define ID_VIEW_SORTRUNS                32822
#define ID_VIEW_RUNS_BY_TRIAL           32823
#define ID_VIEW_HIDDEN                  32824
#define ID_VIEW_TABLE_IN_YPS            32825
#define ID_HELP_CONTENTS                32830
#define ID_HELP_UPDATE                  32831
#define ID_HELP_SPLASH                  32832
#define ID_NEXT_TAB                     32840
#define ID_PREV_TAB                     32841
#define ID_REORDER                      32850
#define ID_EXPAND                       32851
#define ID_COLLAPSE                     32852
#define ID_EXPAND_ALL                   32853
#define ID_COLLAPSE_ALL                 32854
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_FILTERED           59143
#define ID_INDICATOR_DOG                59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        250
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1630
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
