//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgilityBook.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DTD_AGILITYRECORDBOOK       129
#define IDR_XML_DEFAULT_CONFIG          130
#define IDR_DOG                         132
#define IDR_TRIAL                       133
#define IDR_RUN                         134
#define IDR_RUNS                        135
#define IDR_CALENDAR                    136
#define IDR_TRAINING                    137
#define IDI_AGILITYBOOKDOC              150
#define IDI_CALENDAR_EMPTY              151
#define IDI_CALENDAR_TENTATIVE          152
#define IDI_CALENDAR_PLAN               153
#define IDI_CALENDAR_PLAN_TENTATIVE     154
#define IDI_CALENDAR_ENTERED            155
#define IDI_CALENDAR_ENTERED_TENTATIVE  156
#define IDI_CHECKED                     157
#define IDI_UNCHECKED                   158
#define IDI_CRCD                        159
#define IDI_TITLE                       160
#define IDI_TITLE2                      161
#define IDI_HIDDEN                      162
#define IDD_NAME                        200
#define IDD_NAME_DESC                   201
#define IDD_CONFIGURE                   202
#define IDD_CALENDAR                    203
#define IDD_CONFIG_OTHERPOINTS          204
#define IDD_CONFIG_EVENT                205
#define IDD_DOG_PICKER                  206
#define IDD_DOG_POINTS                  207
#define IDD_TITLE                       208
#define IDD_REG_NUM                     209
#define IDD_TRIAL                       210
#define IDD_CLUB                        211
#define IDD_RUN_SCORE                   212
#define IDD_RUN_COMMENTS                213
#define IDD_RUN_REFERENCE               214
#define IDD_RUN_CRCD                    215
#define IDD_REF_RUN                     216
#define IDD_PARTNER                     217
#define IDD_OTHER_POINT                 218
#define IDD_LISTCTRL                    219
#define IDD_FAULT                       220
#define IDD_VIEW_OPTIONS_CALENDAR       221
#define IDD_VIEW_OPTIONS_FILTER         222
#define IDD_VIEW_OPTIONS_FONTS          223
#define IDD_VIEW_OPTIONS_TRAINING       224
#define IDD_REORDER                     225
#define IDD_CONFIG_UPDATE               226
#define IDD_TITLE_POINTS                227
#define IDD_MESSAGE                     228
#define IDD_TRAINING                    229
#define IDD_JUDGE_INFO                  230
#define IDD_WIZARD_START                231
#define IDD_WIZARD_IMPORT               232
#define IDD_WIZARD_EXPORT               233
#define IDD_ASSIGN_COLUMNS              234
#define IDD_FIND                        235
#define IDD_CONFIG_TITLE                236
#define IDD_CONFIG_VENUE                237
#define IDD_DOG_PROP                    238
#define IDD_DOG_TITLES                  239
#define IDD_DOG_NUMBERS                 240
#define IDD_EXISTING_POINTS             241
#define IDD_CRCD_VIEWER                 242
#define IDC_ABOUT_TEXT                  1000
#define IDC_ABOUT_TEXT2                 1001
#define IDC_ABOUT_LINK1                 1002
#define IDC_ABOUT_LINK2                 1003
#define IDC_ABOUT_LINK3                 1004
#define IDC_ABOUT_LINK4                 1005
#define IDC_VENUES                      1014
#define IDC_NAME                        1015
#define IDC_TALLY                       1016
#define IDC_DESC                        1017
#define IDC_PARTNER                     1018
#define IDC_METHODS                     1019
#define IDC_UNUSED                      1020
#define IDC_DIVISION                    1021
#define IDC_LEVEL                       1022
#define IDC_TYPE                        1023
#define IDC_SUPERQ                      1024
#define IDC_MACH                        1025
#define IDC_DOUBLEQ                     1026
#define IDC_ADD                         1027
#define IDC_NEW                         1028
#define IDC_DELETE                      1029
#define IDC_EVENT                       1030
#define IDC_CALLNAME                    1031
#define IDC_DOB                         1032
#define IDC_BREED                       1033
#define IDC_AGE_TEXT                    1034
#define IDC_REG_NAME                    1035
#define IDC_TITLE_NEW                   1036
#define IDC_TITLE_EDIT                  1037
#define IDC_TITLE_DELETE                1038
#define IDC_TITLES                      1039
#define IDC_REG_NUMS                    1043
#define IDC_NOTES                       1044
#define IDC_DATE                        1045
#define IDC_DECEASED                    1046
#define IDC_REG_NUM                     1047
#define IDC_LOCATION                    1048
#define IDC_CLUB_NEW                    1049
#define IDC_CLUB_DELETE                 1050
#define IDC_CLUBS                       1051
#define IDC_VENUE                       1052
#define IDC_CLUB_EDIT                   1053
#define IDC_CLUB                        1054
#define IDC_HEIGHT                      1055
#define IDC_JUDGE                       1056
#define IDC_PARTNERS_EDIT               1057
#define IDC_CONDITIONS                  1058
#define IDC_FAULTS                      1059
#define IDC_YARDS_TEXT                  1060
#define IDC_YARDS                       1061
#define IDC_YPS_TEXT                    1062
#define IDC_YPS                         1063
#define IDC_SCT_TEXT                    1064
#define IDC_SCT                         1065
#define IDC_TOTAL_FAULTS_TEXT           1066
#define IDC_TOTAL_FAULTS                1067
#define IDC_OPENING_PTS_TEXT            1068
#define IDC_OPENING_PTS                 1069
#define IDC_CLOSING_PTS_TEXT            1070
#define IDC_CLOSING_PTS                 1071
#define IDC_OPEN_PTS_TEXT               1072
#define IDC_OPEN_PTS                    1073
#define IDC_CLOSE_PTS_TEXT              1074
#define IDC_CLOSE_PTS                   1075
#define IDC_PLACE                       1076
#define IDC_IN_CLASS                    1077
#define IDC_DOGS_QD                     1078
#define IDC_Q                           1079
#define IDC_SCORE                       1080
#define IDC_TITLE_POINTS_TEXT           1081
#define IDC_TITLE_POINTS                1082
#define IDC_MACHPTS_TEXT                1083
#define IDC_MACHPTS                     1084
#define IDC_DOUBLE_Q                    1085
#define IDC_COMMENTS_FAULTS             1086
#define IDC_FAULTS_LIST                 1087
#define IDC_COMMENTS                    1088
#define IDC_REF_RUNS                    1089
#define IDC_EDIT                        1090
#define IDC_OTHERPOINTS                 1091
#define IDC_DATE_START                  1092
#define IDC_DATE_END                    1093
#define IDC_TENTATIVE                   1094
#define IDC_ENTER_NOT                   1095
#define IDC_ENTER_PLANNING              1096
#define IDC_ENTER_ENTERED               1097
#define IDC_DATE_OPENS                  1098
#define IDC_DATE_OPENS_UNKNOWN          1099
#define IDC_DATE_CLOSES                 1100
#define IDC_DATE_CLOSES_UNKNOWN         1101
#define IDC_POINTS                      1102
#define IDC_TIME                        1103
#define IDC_HANDLER                     1104
#define IDC_CRCD                        1105
#define IDC_LIST                        1106
#define IDC_AUTO_DELETE                 1107
#define IDC_HIDE_OLD                    1108
#define IDC_OLD_ENTRY_DAYS              1109
#define IDC_HIDE_OVERLAP                1110
#define IDC_DAY_OF_WEEK                 1111
#define IDC_SIZE_X                      1112
#define IDC_SIZE_Y                      1113
#define IDC_OPTIONS_DATES_ALL           1114
#define IDC_OPTIONS_DATES_RANGE         1115
#define IDC_OPTIONS_DATE_START_CHECK    1116
#define IDC_OPTIONS_DATE_END_CHECK      1117
#define IDC_OPTIONS_DATE_START          1118
#define IDC_OPTIONS_DATE_END            1119
#define IDC_OPTIONS_VENUES_ALL          1120
#define IDC_OPTIONS_VENUES_SELECTED     1121
#define IDC_OPTIONS_VENUES              1122
#define IDC_OPTIONS_RUNS_ALL            1123
#define IDC_OPTIONS_RUNS_Q              1124
#define IDC_OPTIONS_RUNS_NON_Q          1125
#define IDC_FONT_GENERAL_PRINT          1126
#define IDC_FONT_GENERAL_PRINT_TEXT     1127
#define IDC_FONT_CAL_VIEW_DATE          1128
#define IDC_FONT_CAL_VIEW_DATE_TEXT     1129
#define IDC_FONT_CAL_VIEW_TEXT          1130
#define IDC_FONT_CAL_VIEW_TEXT_TEXT     1131
#define IDC_FONT_CAL_PRINT_DATE         1132
#define IDC_FONT_CAL_PRINT_DATE_TEXT    1133
#define IDC_FONT_CAL_PRINT_TEXT         1134
#define IDC_FONT_CAL_PRINT_TEXT_TEXT    1135
#define IDC_RECEIVED                    1136
#define IDC_TRIAL                       1137
#define IDC_MOVE_UP                     1138
#define IDC_MOVE_DOWN                   1139
#define IDC_UPDATE                      1140
#define IDC_UPDATE_DEFAULT              1141
#define IDC_UPDATE_EXISTING             1142
#define IDC_FILENAME                    1143
#define IDC_DROP_FRACTIONS              1144
#define IDC_VERIFIED                    1145
#define IDC_IS_DECEASED                 1146
#define IDC_WIZARD_SPREADSHEET          1147
#define IDC_WIZARD_ARB                  1148
#define IDC_WIZARD_LIST                 1149
#define IDC_WIZARD_DESCRIPTION          1150
#define IDC_IMPORT_ROW                  1151
#define IDC_IMPORT_ROW_SPIN             1152
#define IDC_WIZARD_DELIM_TAB            1153
#define IDC_WIZARD_DELIM_SPACE          1154
#define IDC_WIZARD_DELIM_COLON          1155
#define IDC_WIZARD_DELIM_SEMI           1156
#define IDC_WIZARD_DELIM_COMMA          1157
#define IDC_WIZARD_DELIM_OTHER          1158
#define IDC_WIZARD_DELIM                1159
#define IDC_WIZARD_ASSIGN               1160
#define IDC_IMPORT_FILE                 1161
#define IDC_IMPORT_PREVIEW_FILE         1162
#define IDC_WIZARD_PREVIEW              1163
#define IDC_COLUMNS                     1164
#define IDC_AVAILABLE                   1165
#define IDC_COPY                        1166
#define IDC_DATE_VALID_FROM             1167
#define IDC_DATE_VALID_TO               1168
#define IDC_SEARCH_ALL                  1169
#define IDC_SEARCH_VISIBLE              1170
#define IDC_MATCH_CASE                  1171
#define IDC_FIND_UP                     1172
#define IDC_FIND_DOWN                   1173
#define IDC_LONG_NAME                   1174
#define IDC_TABLE_YPS                   1175
#define IDC_VIEW                        1176
#define IDC_HIDDEN                      1177
#define IDC_EARNED                      1178
#define IDS_COL_BREED                   4000
#define IDS_COL_CLOSES                  4001
#define IDS_COL_CLUB                    4002
#define IDS_COL_DATE                    4003
#define IDS_COL_DIVISION                4004
#define IDS_COL_DOG                     4005
#define IDS_COL_END_DATE                4006
#define IDS_COL_EVENT                   4007
#define IDS_COL_FAULT                   4008
#define IDS_COL_HANDLER                 4009
#define IDS_COL_IN_CLASS                4010
#define IDS_COL_JUDGE                   4011
#define IDS_COL_LEVEL                   4012
#define IDS_COL_LOCATION                4013
#define IDS_COL_NAME                    4014
#define IDS_COL_NOTE                    4015
#define IDS_COL_NOTES                   4016
#define IDS_COL_NUMBER                  4017
#define IDS_COL_OPENS                   4018
#define IDS_COL_PLACE                   4019
#define IDS_COL_POINTS                  4020
#define IDS_COL_PTS                     4021
#define IDS_COL_Q                       4022
#define IDS_COL_Q_D                     4023
#define IDS_COL_RECEIVED                4024
#define IDS_COL_SCORE                   4025
#define IDS_COL_START_DATE              4026
#define IDS_COL_TIME                    4027
#define IDS_COL_VENUE                   4028
#define IDS_COL_HEIGHT                  4029
#define IDS_COL_REG_NAME                4030
#define IDS_COL_CALLNAME                4031
#define IDS_COL_TRIALNOTES              4032
#define IDS_COL_CONDITIONS              4033
#define IDS_COL_COURSEFAULTS            4034
#define IDS_COL_YARDS                   4035
#define IDS_COL_YPS                     4036
#define IDS_COL_SCT                     4037
#define IDS_COL_TOTAL_FAULTS            4038
#define IDS_COL_REQ_OPENING             4039
#define IDS_COL_REQ_CLOSING             4040
#define IDS_COL_OPENING                 4041
#define IDS_COL_CLOSING                 4042
#define IDS_COL_REQ_POINTS              4043
#define IDS_COL_TITLE_PTS               4044
#define IDS_COL_COMMENTS                4045
#define IDS_COL_FAULTS                  4046
#define IDS_COL_TENTATIVE               4047
#define IDS_COL_ENTERED                 4048
#define IDS_COL_DOB                     4049
#define IDS_COL_AGE                     4050
#define IDS_COL_TYPE                    4051
#define IDS_COL_TITLE                   4052
#define IDS_RUNS                        5000
#define IDS_POINTS                      5001
#define IDS_CALENDAR                    5002
#define IDS_TRAINING                    5003
#define IDS_PARTNERS                    5010
#define IDS_VENUES                      5011
#define IDS_VENUE_NAME                  5012
#define IDS_FAULT_TYPES                 5013
#define IDS_FAULT_TYPE_NAME             5014
#define IDS_OTHERPOINTS                 5015
#define IDS_OTHERPOINTS_NAME            5016
#define IDS_DIVISIONS                   5017
#define IDS_DIVISION_NAME               5018
#define IDS_TITLES                      5019
#define IDS_LEVELS                      5021
#define IDS_LEVEL_NAME                  5022
#define IDS_SUBLEVEL_NAME               5023
#define IDS_EVENTS                      5024
#define IDS_EVENT_NAME                  5025
#define IDS_SCORING                     5026
#define IDS_Q                           5027
#define IDS_SQ                          5028
#define IDS_SUPER_Q                     5029
#define IDS_QQ                          5030
#define IDS_DOUBLE_Q                    5031
#define IDS_MACHPTS                     5032
#define IDS_ABOUT_TEXT                  5080
#define IDS_HELP_UPDATE                 5081
#define IDS_ABOUT_LINK_YAHOO            5082
#define IDS_ABOUT_LINK_EMAILHELP        5083
#define IDS_ABOUT_LINK_ARB              5084
#define IDS_ABOUT_LINK_SOURCEFORGE      5085
#define IDS_UPDATE_NEWER_VERSION        5086
#define IDS_UPDATE_CURRENT              5087
#define IDS_UPDATE_UNKNOWN              5088
#define IDS_NEW                         5091
#define IDS_CONFIGURE                   5092
#define IDS_SCORING_NAME                5093
#define IDS_DELETE_VENUE                5094
#define IDS_DELETE_OTHERPOINTS          5095
#define IDS_DELETE_DIVISION             5096
#define IDS_DELETE_LEVEL                5097
#define IDS_DELETE_TITLE                5098
#define IDS_DELETE_EVENT                5099
#define IDS_DELETE_ALL                  5100
#define IDS_DELETE_ALL_OTHERPOINTS      5101
#define IDS_DELETE_ALL_TITLES           5102
#define IDS_NAME_IN_USE                 5103
#define IDS_ALL                         5104
#define IDS_TITLEPTS_EXISTS             5105
#define IDS_MIN_RESOLUTION              5106
#define IDS_CANNOT_OPEN                 5107
#define IDS_VIEWING_OPTIONS             5108
#define IDS_RUN_PROPERTIES              5109
#define IDS_CONFIG_DELETE_RUNS          5110
#define IDS_SELECT_DIVISION             5111
#define IDS_SELECT_LEVEL                5112
#define IDS_SELECT_EVENT                5113
#define IDS_SELECT_JUDGE                5115
#define IDS_SELECT_Q                    5116
#define IDS_BAD_EVENT                   5117
#define IDS_BAD_SCORINGMETHOD           5118
#define IDS_SCORING_REQUIRED_POINTS     5119
#define IDS_SCORING_POINTS              5120
#define IDS_NUM_EVENTS                  5121
#define IDS_NUM_RUNS_QS                 5122
#define IDS_AUTODELETE_CAL              5123
#define IDS_CREATETRIAL_FAILED          5124
#define IDS_NEED_CLUB                   5125
#define IDS_VENUE_CONFIG_MISSING        5126
#define IDS_DELETE_DOG_DATA             5127
#define IDS_DELETE_TRIAL_DATA           5128
#define IDS_DELETE_EVENT_DATA           5129
#define IDS_COPYOF                      5130
#define IDS_CHANGEDIV_ISSUES            5131
#define IDS_CHANGELEVEL_ISSUES          5132
#define IDS_CHANGESUBLEVEL_ISSUES       5133
#define IDS_NOCONFIGDATA_FOUND          5134
#define IDS_UNKNOWN_DOCUMENT_VERSION    5135
#define IDS_OTHERPTS_ALL                5136
#define IDS_OTHERPTS_EVENT              5137
#define IDS_OTHERPTS_LEVEL              5138
#define IDS_OTHERPTS_EVENT_LEVEL        5139
#define IDS_CONFIG_NO_UPDATE            5140
#define IDS_XERCES_ERROR                5141
#define IDS_POINTS_RUNS_JUDGES          5142
#define IDS_POINTS_PARTNERS             5143
#define IDS_POINTS_QS                   5144
#define IDS_POINTS_CLEAN                5145
#define IDS_POINTS_JUDGES               5146
#define IDS_POINTS_SQS                  5147
#define IDS_POINTS_MACH_SUBTOTAL        5148
#define IDS_POINTS_QQS                  5149
#define IDS_POINTS_MACH                 5150
#define IDS_CONFIG_TITLEPTS             5151
#define IDS_FILEEXT_DEF_ARB             5152
#define IDS_FILEEXT_FNAME_ARB           5153
#define IDS_FILEEXT_FILTER_ARB          5154
#define IDS_CREATERUN_FAILED            5155
#define IDS_CREATETRIAL_FILTERED        5156
#define IDS_CREATERUN_FILTERED          5157
#define IDS_NUM_TRAINING                5158
#define IDS_FILEEXT_DEF_DTD             5159
#define IDS_FILEEXT_FNAME_DTD           5160
#define IDS_FILEEXT_FILTER_DTD          5161
#define IDS_FILEEXT_DEF_XML             5162
#define IDS_FILEEXT_FNAME_XML           5163
#define IDS_FILEEXT_FILTER_XML          5164
#define IDS_ADDED_CAL_ITEMS             5165
#define IDS_FILEEXT_FILTER_TXT          5166
#define IDS_FILE_PREVIEW                5167
#define IDS_BLANK_COLUMN                5168
#define IDS_ADDED_TRAINING_ITEMS        5169
#define ID_FILE_EXPORT_WIZARD           32772
#define ID_FILE_AUTOCHECK               32773
#define ID_EDIT_CONFIGURATION           32774
#define ID_HELP_UPDATE                  32775
#define ID_VIEW_HIDDEN                  32776
#define ID_AGILITY_NEW_CALENDAR         32779
#define ID_AGILITY_NEW_TRAINING         32780
#define ID_AGILITY_NEW_DOG              32781
#define ID_AGILITY_NEW_TITLE            32782
#define ID_AGILITY_NEW_TRIAL            32783
#define ID_AGILITY_NEW_RUN              32784
#define ID_AGILITY_EDIT_CALENDAR        32785
#define ID_AGILITY_EDIT_TRAINING        32786
#define ID_AGILITY_EDIT_DOG             32787
#define ID_AGILITY_EDIT_TITLE           32788
#define ID_AGILITY_EDIT_TRIAL           32789
#define ID_AGILITY_EDIT_RUN             32790
#define ID_AGILITY_DELETE_CALENDAR      32791
#define ID_AGILITY_DELETE_TRAINING      32792
#define ID_AGILITY_DELETE_DOG           32793
#define ID_AGILITY_DELETE_TITLE         32794
#define ID_AGILITY_DELETE_TRIAL         32795
#define ID_AGILITY_DELETE_RUN           32796
#define ID_AGILITY_CREATEENTRY_CALENDAR 32797
#define ID_VIEW_OPTIONS                 32798
#define ID_EXPAND                       32799
#define ID_EXPAND_ALL                   32800
#define ID_COLLAPSE                     32801
#define ID_COLLAPSE_ALL                 32802
#define ID_NEXT_TAB                     32803
#define ID_PREV_TAB                     32804
#define ID_REORDER                      32805
#define ID_VIEW_SORTRUNS                32806
#define ID_VIEW_RUNS_BY_TRIAL           32807
#define ID_EDIT_JUDGES                  32808
#define ID_EDIT_FIND_NEXT               32809
#define ID_EDIT_FIND_PREVIOUS           32810
#define ID_VIEW_CUSTOMIZE               32811
#define ID_VIEW_TABLE_IN_YPS            32812
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_FILTERED           59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
