//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgilityBook.rc
//
#define IDB_LOGO                        101
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_DTD_AGILITYRECORDBOOK       129
#define IDR_XML_DEFAULT_CONFIG          130
#define IDR_DOG                         132
#define IDR_TRIAL                       133
#define IDR_RUN                         134
#define IDR_POINTS                      135
#define IDR_CALENDAR                    136
#define IDR_TRAINING                    137
#define IDI_AGILITYBOOKDOC              150
#define IDI_EMPTY                       151
#define IDI_QUESTIONMARK                152
#define IDI_CHECKMARK                   153
#define IDI_CALENDAR_PLAN_TENTATIVE     154
#define IDI_CALENDAR_ENTERED            155
#define IDI_CALENDAR_ENTERED_TENTATIVE  156
#define IDI_CHECKED                     157
#define IDI_UNCHECKED                   158
#define IDI_CRCD                        159
#define IDI_TITLE                       160
#define IDI_TITLE2                      161
#define IDI_HIDDEN                      162
#define IDI_HEADER_UP                   163
#define IDI_HEADER_DOWN                 164
#define IDI_HELP                        165
#define IDI_NOTEBTN                     166
#define IDI_DOG                         167
#define IDI_TRIAL                       168
#define IDI_RUN                         169
#define IDI_ACCOMMODATION_NONE          170
#define IDI_ACCOMMODATION_TODO          171
#define IDI_ACCOMMODATION_CONFIRMED     172
#define IDI_VENUE_AAC                   173
#define IDI_VENUE_AKC                   174
#define IDI_VENUE_ASCA                  175
#define IDI_VENUE_CKC                   176
#define IDI_VENUE_CPE                   177
#define IDI_VENUE_DOCNA                 178
#define IDI_VENUE_NADAC                 179
#define IDI_VENUE_SWEEP                 180
#define IDI_VENUE_TDAA                  181
#define IDI_VENUE_UKC                   182
#define IDI_VENUE_USDAA                 183
#define IDI_VENUE_FCI                   184
#define IDI_VENUE_SCC                   185
#define IDD_ABOUTBOX                    200
#define IDD_NAME                        201
#define IDD_LIST_VIEWER                 202
#define IDD_LISTCTRL                    203
#define IDD_MESSAGE                     204
#define IDD_FIND                        205
#define IDD_CONFIGURE                   206
#define IDD_CONFIG_VENUE                207
#define IDD_CONFIG_EVENT                208
#define IDD_CONFIG_OTHERPOINTS          209
#define IDD_CONFIG_TITLE                210
#define IDD_CONFIG_UPDATE               211
#define IDD_CALENDAR                    212
#define IDD_TRAINING                    213
#define IDD_JUDGE_INFO                  214
#define IDD_DOG_PICKER                  215
#define IDD_DOG_POINTS                  216
#define IDD_DOG_PROP                    217
#define IDD_DOG_TITLES                  218
#define IDD_DOG_NUMBERS                 219
#define IDD_REG_NUM                     220
#define IDD_TITLE                       221
#define IDD_EXISTING_POINTS             222
#define IDD_TRIAL                       223
#define IDD_CLUB                        224
#define IDD_RUN_SCORE                   225
#define IDD_RUN_COMMENTS                226
#define IDD_RUN_REFERENCE               227
#define IDD_RUN_CRCD                    228
#define IDD_RUN_LINK                    229
#define IDD_REF_RUN                     230
#define IDD_PARTNER                     231
#define IDD_OTHER_POINT                 232
#define IDD_FAULT                       233
#define IDD_CONFIG_TITLE_POINTS         234
#define IDD_CRCD_VIEWER                 235
#define IDD_SELECT_URL                  236
#define IDD_VIEW_OPTIONS_PROGRAM        237
#define IDD_VIEW_OPTIONS_FILTER         238
#define IDD_VIEW_OPTIONS_CALENDAR       239
#define IDD_CONFIG_EVENT_METHOD         240
#define IDD_CONFIG_PLACEINFO            241
#define IDD_VIEW_OPTIONS_PRINTING       242
#define IDD_REORDER                     243
#define IDD_WIZARD_START                244
#define IDD_WIZARD_IMPORT               245
#define IDD_WIZARD_EXPORT               246
#define IDD_ASSIGN_COLUMNS              247
#define IDD_FIND_LINKS                  248
#define IDD_MESSAGE_BOX                 249
#define IDD_PROGRESS_DLG                250
#define IDD_CONFIG_MULTI_Q              251
#define IDD_EVENT_SELECT                252
#define IDD_AUTHENTICATE                253
#define IDD_POINTS_VIEW_SORT            254
#define IDD_LANGUAGE                    255
#define IDC_ABOUT_TEXT                  1000
#define IDC_ABOUT_TEXT2                 1001
#define IDC_ABOUT_LINK1                 1002
#define IDC_ABOUT_LINK2                 1003
#define IDC_ABOUT_LINK3                 1004
#define IDC_ABOUT_LINK4                 1005
#define IDC_ABOUT_UPDATE                1006
#define IDC_NAME                        1010
#define IDC_MESSAGE                     1011
#define IDC_FIND_NAME                   1012
#define IDC_FIND_CASE                   1013
#define IDC_FIND_ALL                    1014
#define IDC_FIND_VISIBLE                1015
#define IDC_FIND_UP                     1016
#define IDC_FIND_DOWN                   1017
#define IDC_LIST_VIEWER                 1020
#define IDC_LIST_COPY                   1021
#define IDC_LIST                        1022
#define IDC_LIST_NEW                    1023
#define IDC_LIST_EDIT                   1024
#define IDC_LIST_DELETE                 1025
#define IDC_LIST_MOVE_UP                1026
#define IDC_LIST_MOVE_DOWN              1027
#define IDC_LIST_TRIAL                  1028
#define IDC_CONFIG_ITEMS                1030
#define IDC_CONFIG_NEW                  1031
#define IDC_CONFIG_EDIT                 1032
#define IDC_CONFIG_DELETE               1033
#define IDC_CONFIG_COPY                 1034
#define IDC_CONFIG_UPDATE               1038
#define IDC_CONFIG_VENUE                1040
#define IDC_CONFIG_VENUE_DESC           1041
#define IDC_CONFIG_VENUE_DIVISION       1042
#define IDC_CONFIG_VENUE_LEVEL          1043
#define IDC_CONFIG_VENUE_NEW            1044
#define IDC_CONFIG_VENUE_DELETE         1045
#define IDC_CONFIG_VENUE_EDIT           1046
#define IDC_CONFIG_VENUE_COPY           1047
#define IDC_CONFIG_VENUE_MOVE_UP        1048
#define IDC_CONFIG_VENUE_MOVE_DOWN      1049
#define IDC_CONFIG_VENUE_COMMENTS       1050
#define IDC_CONFIG_VENUE_EVENT          1051
#define IDC_CONFIG_VENUE_TITLES         1052
#define IDC_CONFIG_VENUE_LONGNAME       1053
#define IDC_CONFIG_VENUE_MULTIQ         1054
#define IDC_CONFIG_VENUE_URL            1055
#define IDC_CONFIG_EVENT                1060
#define IDC_CONFIG_EVENT_TABLE          1061
#define IDC_CONFIG_EVENT_PARTNER        1062
#define IDC_CONFIG_EVENT_HAS_SUBNAMES   1063
#define IDC_CONFIG_EVENT_SUBNAMES       1064
#define IDC_CONFIG_EVENT_SUBNAMES_NEW   1065
#define IDC_CONFIG_EVENT_SUBNAMES_EDIT  1066
#define IDC_CONFIG_EVENT_SUBNAMES_DELETE 1067
#define IDC_CONFIG_EVENT_DESC           1068
#define IDC_CONFIG_EVENT_METHODS        1069
#define IDC_CONFIG_EVENT_UNUSED         1070
#define IDC_CONFIG_EVENT_NEW            1071
#define IDC_CONFIG_EVENT_EDIT           1072
#define IDC_CONFIG_EVENT_DELETE         1073
#define IDC_CONFIG_EVENT_COPY           1074
#define IDC_CONFIG_EVENT_MOVE_UP        1075
#define IDC_CONFIG_EVENT_MOVE_DOWN      1076
#define IDC_CONFIG_EVENT_POINTS         1077
#define IDC_CONFIG_EVENT_POINTS_NEW     1078
#define IDC_CONFIG_EVENT_POINTS_EDIT    1079
#define IDC_CONFIG_EVENT_POINTS_DELETE  1080
#define IDC_CONFIG_EVENT_NOTES          1081
#define IDC_CONFIG_EVENT_INFO           1082
#define IDC_CONFIG_EVENT_DIVISION       1090
#define IDC_CONFIG_EVENT_LEVEL          1091
#define IDC_CONFIG_EVENT_DATE_VALID_FROM 1092
#define IDC_CONFIG_EVENT_DATE_START     1093
#define IDC_CONFIG_EVENT_DATE_VALID_TO  1094
#define IDC_CONFIG_EVENT_DATE_END       1095
#define IDC_CONFIG_EVENT_TYPE           1096
#define IDC_CONFIG_EVENT_DROP_FRACTIONS 1097
#define IDC_CONFIG_EVENT_BONUS          1098
#define IDC_CONFIG_EVENT_SUPERQ         1099
#define IDC_CONFIG_EVENT_SPEED          1100
#define IDC_CONFIG_EVENT_TF_MULTIPLY_TEXT 1101
#define IDC_CONFIG_EVENT_TF_MULTIPLY    1102
#define IDC_CONFIG_EVENT_PLACEMENT_TEXT 1103
#define IDC_CONFIG_EVENT_PLACEMENT      1104
#define IDC_CONFIG_EVENT_PLACEMENT_NEW  1105
#define IDC_CONFIG_EVENT_PLACEMENT_EDIT 1106
#define IDC_CONFIG_EVENT_PLACEMENT_DELETE 1107
#define IDC_CONFIG_EVENT_TIME_FAULTS_CLEANQ 1108
#define IDC_CONFIG_EVENT_TIME_FAULTS_UNDER 1109
#define IDC_CONFIG_EVENT_TIME_FAULTS_OVER 1110
#define IDC_CONFIG_EVENT_SUBTRACT_TIME_FAULTS 1111
#define IDC_CONFIG_EVENT_OPENING_PTS_TEXT 1112
#define IDC_CONFIG_EVENT_OPENING_PTS    1113
#define IDC_CONFIG_EVENT_CLOSING_PTS_TEXT 1114
#define IDC_CONFIG_EVENT_CLOSING_PTS    1115
#define IDC_CONFIG_PLACEINFO_PLACE      1120
#define IDC_CONFIG_PLACEINFO_VALUE      1121
#define IDC_CONFIG_OTHER_NAME           1130
#define IDC_CONFIG_OTHER_TALLY          1131
#define IDC_CONFIG_OTHER_DESC           1132
#define IDC_CONFIG_OTHER_DEFAULT        1133
#define IDC_CONFIG_TITLE_NAME           1140
#define IDC_CONFIG_TITLE_LONG_NAME      1141
#define IDC_CONFIG_TITLE_DESC           1142
#define IDC_CONFIG_TITLE_ALLOW_MULTIPLE 1143
#define IDC_CONFIG_TITLE_MULTIPLE       1144
#define IDC_CONFIG_TITLE_PREFIX         1145
#define IDC_CONFIG_TITLE_VALID_FROM     1146
#define IDC_CONFIG_TITLE_VALID_FROM_DATE 1147
#define IDC_CONFIG_TITLE_VALID_TO       1148
#define IDC_CONFIG_TITLE_VALID_TO_DATE  1149
#define IDC_CONFIG_UPDATE_DEFAULT       1150
#define IDC_CONFIG_UPDATE_EXISTING      1151
#define IDC_CONFIG_UPDATE_NAME          1152
#define IDC_CONFIG_UPDATE_FILENAME      1153
#define IDC_CAL_DATE_START              1160
#define IDC_CAL_DATE_END                1161
#define IDC_CAL_TENTATIVE               1162
#define IDC_CAL_ENTER_NOT               1163
#define IDC_CAL_ENTER_PLANNING          1164
#define IDC_CAL_ENTER_ENTERED           1165
#define IDC_CAL_LOCATION                1166
#define IDC_CAL_CLUB                    1167
#define IDC_CAL_VENUE                   1168
#define IDC_CAL_DATE_OPENS              1169
#define IDC_CAL_DATE_OPENS_UNKNOWN      1170
#define IDC_CAL_DATE_CLOSES             1171
#define IDC_CAL_DATE_CLOSES_UNKNOWN     1172
#define IDC_CAL_NOTES                   1173
#define IDC_CAL_LOCATION_NOTE           1174
#define IDC_CAL_CLUB_NOTE               1175
#define IDC_CAL_LOCATION_NOTES          1176
#define IDC_CAL_CLUB_NOTES              1177
#define IDC_CAL_DATE_DRAWS              1178
#define IDC_CAL_DATE_DRAWS_UNKNOWN      1179
#define IDC_CAL_ACCOM_NONE              1180
#define IDC_CAL_ACCOM_NEEDED            1181
#define IDC_CAL_ACCOM_MADE              1182
#define IDC_CAL_ACCOM_CONFIRMATION      1183
#define IDC_CAL_ONLINE_URL              1184
#define IDC_CAL_ONLINE_ENTRY            1185
#define IDC_CAL_EMAIL_SEC_ADDR          1186
#define IDC_CAL_EMAIL_SEC               1187
#define IDC_CAL_PREMIUM_URL             1188
#define IDC_CAL_PREMIUM_ENTRY           1189
#define IDC_JUDGE                       1201
#define IDC_JUDGE_NEW                   1202
#define IDC_JUDGE_DELETE                1203
#define IDC_JUDGE_COMMENTS              1204
#define IDC_TRAINING_DATE               1205
#define IDC_TRAINING_NAME               1206
#define IDC_TRAINING_NOTES              1207
#define IDC_TRAINING_SUBNAME            1208
#define IDC_PICK_NAME                   1209
#define IDC_DOGPTS_POINTS               1210
#define IDC_DOGPTS_NEW                  1211
#define IDC_DOGPTS_EDIT                 1212
#define IDC_DOGPTS_DELETE               1213
#define IDC_DOGPTS_SELECTED_PTS         1214
#define IDC_DOG_CALLNAME                1220
#define IDC_DOG_BREED                   1221
#define IDC_DOG_REG_NAME                1222
#define IDC_DOG_AGE_TEXT                1223
#define IDC_DOG_DOB                     1224
#define IDC_DOG_IS_DECEASED             1225
#define IDC_DOG_DECEASED                1227
#define IDC_DOG_NOTES                   1228
#define IDC_DOG_TITLE_TITLES            1230
#define IDC_DOG_TITLE_NEW               1231
#define IDC_DOG_TITLE_EDIT              1232
#define IDC_DOG_TITLE_DELETE            1233
#define IDC_DOG_TITLE_HIDDEN            1234
#define IDC_DOGNUM_REG_NUMS             1240
#define IDC_DOGNUM_NEW                  1241
#define IDC_DOGNUM_EDIT                 1242
#define IDC_DOGNUM_DELETE               1243
#define IDC_REGNUM_NOTE                 1244
#define IDC_REGNUM_VENUES               1245
#define IDC_REGNUM_REG_NUM              1246
#define IDC_REGNUM_HEIGHT               1247
#define IDC_REGNUM_RECEIVED             1248
#define IDC_TITLE_EARNED                1250
#define IDC_TITLE_DATE                  1251
#define IDC_TITLE_HIDDEN                1252
#define IDC_TITLE_VENUES                1253
#define IDC_TITLE_TITLES                1254
#define IDC_TITLE_RECEIVED              1255
#define IDC_TITLE_DESC                  1256
#define IDC_EXISTING_DATE               1260
#define IDC_EXISTING_TYPE               1261
#define IDC_EXISTING_POINTS             1262
#define IDC_EXISTING_OTHERPOINTS_TEXT   1263
#define IDC_EXISTING_OTHERPOINTS        1264
#define IDC_EXISTING_VENUES_TEXT        1265
#define IDC_EXISTING_VENUES             1266
#define IDC_EXISTING_MULTIQ_TEXT        1267
#define IDC_EXISTING_MULTIQ             1268
#define IDC_EXISTING_DIVISION_TEXT      1269
#define IDC_EXISTING_DIVISION           1270
#define IDC_EXISTING_LEVEL_TEXT         1271
#define IDC_EXISTING_LEVEL              1272
#define IDC_EXISTING_EVENT_TEXT         1273
#define IDC_EXISTING_EVENT              1274
#define IDC_EXISTING_SUBNAME_TEXT       1275
#define IDC_EXISTING_SUBNAME            1276
#define IDC_EXISTING_COMMENTS           1277
#define IDC_TRIAL_LOCATION_NOTES        1278
#define IDC_TRIAL_CLUB_NOTES            1279
#define IDC_TRIAL_LOCATION              1280
#define IDC_TRIAL_NOTES                 1281
#define IDC_TRIAL_CLUB_NEW              1282
#define IDC_TRIAL_CLUB_EDIT             1283
#define IDC_TRIAL_CLUB_DELETE           1284
#define IDC_TRIAL_CLUBS                 1285
#define IDC_TRIAL_VERIFIED              1286
#define IDC_TRIAL_LOCATION_INFO         1287
#define IDC_TRIAL_CLUB_INFO             1288
#define IDC_CLUB_CLUBS                  1290
#define IDC_CLUB_VENUES                 1291
#define IDC_RUNSCORE_DATE               1300
#define IDC_RUNSCORE_VENUE              1301
#define IDC_RUNSCORE_CLUB               1302
#define IDC_RUNSCORE_LOCATION           1303
#define IDC_RUNSCORE_DIVISION           1304
#define IDC_RUNSCORE_LEVEL              1305
#define IDC_RUNSCORE_EVENT              1306
#define IDC_RUNSCORE_DESC               1307
#define IDC_RUNSCORE_HEIGHT             1308
#define IDC_RUNSCORE_JUDGE              1309
#define IDC_RUNSCORE_HANDLER            1310
#define IDC_RUNSCORE_CONDITIONS         1311
#define IDC_RUNSCORE_PARTNERS_EDIT      1312
#define IDC_RUNSCORE_PARTNER            1313
#define IDC_RUNSCORE_FAULTS_TEXT        1314
#define IDC_RUNSCORE_FAULTS             1315
#define IDC_RUNSCORE_TIME_TEXT          1316
#define IDC_RUNSCORE_TIME               1317
#define IDC_RUNSCORE_TABLE              1318
#define IDC_RUNSCORE_OPENING_PTS_TEXT   1319
#define IDC_RUNSCORE_OPENING_PTS        1320
#define IDC_RUNSCORE_CLOSING_PTS_TEXT   1321
#define IDC_RUNSCORE_CLOSING_PTS        1322
#define IDC_RUNSCORE_OPEN_PTS_TEXT      1323
#define IDC_RUNSCORE_OPEN_PTS           1324
#define IDC_RUNSCORE_CLOSE_PTS_TEXT     1325
#define IDC_RUNSCORE_CLOSE_PTS          1326
#define IDC_RUNSCORE_YARDS_TEXT         1327
#define IDC_RUNSCORE_YARDS              1328
#define IDC_RUNSCORE_MIN_YPS_TEXT       1329
#define IDC_RUNSCORE_MIN_YPS            1330
#define IDC_RUNSCORE_YPS_TEXT           1331
#define IDC_RUNSCORE_YPS                1332
#define IDC_RUNSCORE_SCT_TEXT           1333
#define IDC_RUNSCORE_SCT                1334
#define IDC_RUNSCORE_SCT2_TEXT          1335
#define IDC_RUNSCORE_SCT2               1336
#define IDC_RUNSCORE_TOTAL_FAULTS_TEXT  1337
#define IDC_RUNSCORE_TOTAL_FAULTS       1338
#define IDC_RUNSCORE_PLACE              1339
#define IDC_RUNSCORE_IN_CLASS           1340
#define IDC_RUNSCORE_DOGS_QD            1341
#define IDC_RUNSCORE_Q                  1342
#define IDC_RUNSCORE_SCORE              1343
#define IDC_RUNSCORE_SPEEDPTS_TEXT      1344
#define IDC_RUNSCORE_SPEEDPTS           1345
#define IDC_RUNSCORE_TITLE_POINTS_TEXT  1346
#define IDC_RUNSCORE_TITLE_POINTS       1347
#define IDC_RUNSCORE_OTHERPOINTS        1348
#define IDC_RUNSCORE_SUBNAME_TEXT       1349
#define IDC_RUNSCORE_SUBNAME            1350
#define IDC_RUNCOMMENT_COMMENTS         1360
#define IDC_RUNCOMMENT_FAULTS_LIST      1361
#define IDC_RUNCOMMENT_COMMENTS_FAULTS  1362
#define IDC_RUNSCORE_BONUSPTS_TEXT      1363
#define IDC_RUNSCORE_BONUSPTS           1364
#define IDC_RUNSCORE_JUDGE_NOTES        1365
#define IDC_RUNREF_REF_RUNS             1366
#define IDC_RUNREF_NEW                  1367
#define IDC_RUNREF_EDIT                 1368
#define IDC_RUNREF_DELETE               1369
#define IDC_RUNREF_ADDDOG               1370
#define IDC_RUNCRCD_EDIT                1371
#define IDC_RUNCRCD_VIEW                1372
#define IDC_RUNCRCD_COPY                1373
#define IDC_RUNCRCD_CRCD                1374
#define IDC_RUNCRCD_DESC                1375
#define IDC_RUNCRCD_IMAGE               1376
#define IDC_RUNLINK_LIST                1380
#define IDC_RUNLINK_NEW                 1381
#define IDC_RUNLINK_EDIT                1382
#define IDC_RUNLINK_DELETE              1383
#define IDC_RUNLINK_OPEN                1384
#define IDC_REFRUN_PLACE                1390
#define IDC_REFRUN_Q                    1391
#define IDC_REFRUN_HEIGHT               1392
#define IDC_REFRUN_TIME                 1393
#define IDC_REFRUN_NAME                 1394
#define IDC_REFRUN_BREED                1395
#define IDC_REFRUN_NOTES                1396
#define IDC_REFRUN_POINTS               1397
#define IDC_PARTNER_NAME                1400
#define IDC_PARTNER_CALLNAME            1401
#define IDC_PARTNER_REG_NUM             1402
#define IDC_OTHER_OTHERPOINTS           1410
#define IDC_OTHER_DESC                  1411
#define IDC_OTHER_POINTS                1412
#define IDC_OTHER_NEW                   1413
#define IDC_FAULTS                      1420
#define IDC_CONFIG_TITLEPTS_VALUE_TEXT  1430
#define IDC_CONFIG_TITLEPTS_VALUE       1431
#define IDC_CONFIG_TITLEPTS_POINTS      1432
#define IDC_CONFIG_TITLEPTS_TITLE_POINTS 1433
#define IDC_VIEWER_CRCD                 1440
#define IDC_SELECTURL_NAME              1441
#define IDC_SELECTURL_FILENAME          1442
#define IDC_OPT_PGM_AUTO_CHECK          1450
#define IDC_OPT_PGM_EDIT                1451
#define IDC_OPT_PGM_AUTOSHOW            1452
#define IDC_OPT_PGM_SHOW_SPLASH         1453
#define IDC_OPT_PGM_FILENAME            1454
#define IDC_OPT_PGM_BROWSE              1455
#define IDC_OPT_PGM_SHOWHTML            1456
#define IDC_OPT_FILTER_DATE_ALL         1460
#define IDC_OPT_FILTER_DATE_RANGE       1461
#define IDC_OPT_FILTER_DATE_START_CHECK 1462
#define IDC_OPT_FILTER_DATE_START       1463
#define IDC_OPT_FILTER_DATE_END_CHECK   1464
#define IDC_OPT_FILTER_DATE_END         1465
#define IDC_OPT_FILTER_LOG_NAME_ALL     1466
#define IDC_OPT_FILTER_LOG_NAME_SELECTED 1467
#define IDC_OPT_FILTER_LOG_NAME         1468
#define IDC_OPT_FILTER_CAL_NOT_ENTERED  1469
#define IDC_OPT_FILTER_CAL_PLANNING     1470
#define IDC_OPT_FILTER_CAL_ENTERED      1471
#define IDC_OPT_FILTER_RUN_VENUES_ALL   1472
#define IDC_OPT_FILTER_RUN_VENUES_SELECTED 1473
#define IDC_OPT_FILTER_RUN_VENUES       1474
#define IDC_OPT_FILTER_RUN_RUNS_ALL     1475
#define IDC_OPT_FILTER_RUN_RUNS_Q       1476
#define IDC_OPT_FILTER_RUN_RUNS_NON_Q   1477
#define IDC_OPT_FILTER_NAMES            1478
#define IDC_OPT_FILTER_NAMES_DELETE     1479
#define IDC_OPT_FILTER_NAMES_SAVE       1480
#define IDC_OPT_CAL_WARN_OPENNEAR       1490
#define IDC_OPT_CAL_COLOR_OPENNEAR      1491
#define IDC_OPT_CAL_COLOR_OPENNEAR_SET  1492
#define IDC_OPT_CAL_OPENNEAR            1493
#define IDC_OPT_CAL_WARN_CLOSENEAR      1494
#define IDC_OPT_CAL_COLOR_CLOSENEAR     1495
#define IDC_OPT_CAL_COLOR_CLOSENEAR_SET 1496
#define IDC_OPT_CAL_CLOSENEAR           1497
#define IDC_OPT_CAL_DAY_OF_WEEK         1498
#define IDC_OPT_CAL_AUTO_DELETE         1501
#define IDC_OPT_CAL_HIDE_OLD            1502
#define IDC_OPT_CAL_OLD_ENTRY_DAYS      1503
#define IDC_OPT_CAL_HIDE_OVERLAP        1504
#define IDC_OPT_CAL_OPENING             1505
#define IDC_OPT_CAL_CLOSING             1506
#define IDC_OPT_CAL_ENTRIES             1507
#define IDC_OPT_CAL_COLOR               1508
#define IDC_OPT_CAL_COLOR_SET           1509
#define IDC_OPT_CAL_VIEW                1510
#define IDC_OPT_CAL_FONT                1511
#define IDC_OPT_PRINT_FONT_TEXT         1520
#define IDC_OPT_PRINT_FONT              1521
#define IDC_OPT_PRINT_MARGIN_L          1522
#define IDC_OPT_PRINT_MARGIN_T          1523
#define IDC_OPT_PRINT_MARGIN_R          1524
#define IDC_OPT_PRINT_MARGIN_B          1525
#define IDC_REORDER_LIST                1530
#define IDC_REORDER_MOVE_UP             1531
#define IDC_REORDER_MOVE_DOWN           1532
#define IDC_WIZARD_START_EXCEL          1540
#define IDC_WIZARD_START_CALC           1541
#define IDC_WIZARD_START_SPREADSHEET    1542
#define IDC_WIZARD_START_ARB            1543
#define IDC_WIZARD_START_LIST           1544
#define IDC_WIZARD_START_DESCRIPTION    1545
#define IDC_WIZARD_IMPORT_ROW           1550
#define IDC_WIZARD_IMPORT_ROW_SPIN      1551
#define IDC_WIZARD_IMPORT_DELIM_GROUP   1552
#define IDC_WIZARD_IMPORT_DELIM_TAB     1553
#define IDC_WIZARD_IMPORT_DELIM_SPACE   1554
#define IDC_WIZARD_IMPORT_DELIM_COLON   1555
#define IDC_WIZARD_IMPORT_DELIM_SEMI    1556
#define IDC_WIZARD_IMPORT_DELIM_COMMA   1557
#define IDC_WIZARD_IMPORT_DELIM_OTHER   1558
#define IDC_WIZARD_IMPORT_DELIM         1559
#define IDC_WIZARD_IMPORT_DATE          1560
#define IDC_WIZARD_IMPORT_ASSIGN        1561
#define IDC_WIZARD_IMPORT_FILE          1562
#define IDC_WIZARD_IMPORT_PREVIEW_FILE  1563
#define IDC_WIZARD_IMPORT_PREVIEW       1564
#define IDC_WIZARD_EXPORT_DELIM_GROUP   1570
#define IDC_WIZARD_EXPORT_DELIM_TAB     1571
#define IDC_WIZARD_EXPORT_DELIM_SPACE   1572
#define IDC_WIZARD_EXPORT_DELIM_COLON   1573
#define IDC_WIZARD_EXPORT_DELIM_SEMI    1574
#define IDC_WIZARD_EXPORT_DELIM_COMMA   1575
#define IDC_WIZARD_EXPORT_DELIM_OTHER   1576
#define IDC_WIZARD_EXPORT_DELIM         1577
#define IDC_WIZARD_EXPORT_DATE          1578
#define IDC_WIZARD_EXPORT_ASSIGN        1579
#define IDC_WIZARD_EXPORT_PREVIEW       1580
#define IDC_ASSIGN_TYPE                 1590
#define IDC_ASSIGN_AVAILABLE            1591
#define IDC_ASSIGN_ADD                  1592
#define IDC_ASSIGN_DELETE               1593
#define IDC_ASSIGN_MOVE_UP              1594
#define IDC_ASSIGN_MOVE_DOWN            1595
#define IDC_ASSIGN_COLUMNS              1596
#define IDC_FINDLINKS_LIST              1600
#define IDC_FINDLINKS_COPY              1601
#define IDC_FINDLINKS_EDIT              1602
#define IDC_FINDLINKS_OPEN              1603
#define IDC_MESSAGE_BOX_ICON            1610
#define IDC_MESSAGE_BOX_TEXT            1611
#define IDC_MESSAGE_BOX_BUTTON1         1612
#define IDC_MESSAGE_BOX_BUTTON2         1613
#define IDC_MESSAGE_BOX_BUTTON3         1614
#define IDC_MESSAGE_BOX_DETAILS         1615
#define IDC_PROGRESS_MESSAGE            1620
#define IDC_PROGRESS_BAR1               1621
#define IDC_PROGRESS_BAR2               1622
#define IDC_CONFIG_MULTIQ_SHORTNAME     1630
#define IDC_CONFIG_MULTIQ_NAME          1631
#define IDC_CONFIG_MULTIQ_DATE_VALID_FROM 1632
#define IDC_CONFIG_MULTIQ_DATE_START    1633
#define IDC_CONFIG_MULTIQ_DATE_VALID_TO 1634
#define IDC_CONFIG_MULTIQ_DATE_END      1635
#define IDC_CONFIG_MULTIQ_ITEMS         1636
#define IDC_CONFIG_MULTIQ_ADD           1637
#define IDC_CONFIG_MULTIQ_EDIT          1638
#define IDC_CONFIG_MULTIQ_DELETE        1639
#define IDC_EVENT_SELECT_DIVISION       1640
#define IDC_EVENT_SELECT_LEVEL          1641
#define IDC_EVENT_SELECT_EVENT          1642
#define IDC_POINTS_VIEW_SORT_C1         1660
#define IDC_POINTS_VIEW_SORT_C2         1661
#define IDC_POINTS_VIEW_SORT_C3         1662
#define IDC_AUTH_USERNAME               1670
#define IDC_AUTH_PASSWORD               1671
#define IDC_LANGUAGE                    1672
#define IDS_BUTTON_OK                   4000
#define IDS_BUTTON_CANCEL               4001
#define IDS_BUTTON_YES                  4002
#define IDS_BUTTON_NO                   4003
#define IDS_BUTTON_ABORT                4004
#define IDS_BUTTON_IGNORE               4005
#define IDS_BUTTON_RETRY                4006
#define IDS_COL_ACTUAL_WORK             4010
#define IDS_COL_AGE                     4011
#define IDS_COL_ALL_DAY_EVENT           4012
#define IDS_COL_BILLING                 4020
#define IDS_COL_BREED                   4021
#define IDS_COL_CALLNAME                4022
#define IDS_COL_CATEGORIES              4023
#define IDS_COL_CLOSES                  4024
#define IDS_COL_CLOSING                 4025
#define IDS_COL_CLUB                    4026
#define IDS_COL_COMMENTS                4027
#define IDS_COL_COMPANIES               4028
#define IDS_COL_COMPLETE                4029
#define IDS_COL_COMPLETED_DATE          4030
#define IDS_COL_CONDITIONS              4031
#define IDS_COL_CONTACTS                4032
#define IDS_COL_COURSEFAULTS            4033
#define IDS_COL_DATE                    4040
#define IDS_COL_DESCRIPTION             4041
#define IDS_COL_DIVISION                4042
#define IDS_COL_DIVISIONS               4043
#define IDS_COL_DOB                     4044
#define IDS_COL_DOG                     4045
#define IDS_COL_DUE_DATE                4046
#define IDS_COL_DRAWS                   4047
#define IDS_COL_END_DATE                4050
#define IDS_COL_END_TIME                4051
#define IDS_COL_ENTERED                 4052
#define IDS_COL_EVENT                   4053
#define IDS_COL_EVENTS                  4054
#define IDS_COL_FAULT                   4060
#define IDS_COL_FAULTS                  4061
#define IDS_COL_HANDLER                 4080
#define IDS_COL_HEIGHT                  4081
#define IDS_COL_IN_CLASS                4090
#define IDS_COL_JUDGE                   4091
#define IDS_COL_LEVEL                   4110
#define IDS_COL_LOCATION                4111
#define IDS_COL_MILEAGE                 4120
#define IDS_COL_MIN_YPS                 4121
#define IDS_COL_MULTIPLIER              4122
#define IDS_COL_MULTIQ                  4123
#define IDS_COL_NAME                    4130
#define IDS_COL_NOTE                    4131
#define IDS_COL_NOTES                   4132
#define IDS_COL_NUMBER                  4133
#define IDS_COL_OPENING                 4140
#define IDS_COL_OPENS                   4141
#define IDS_COL_OPT_ATTENDEES           4142
#define IDS_COL_ORGANIZER               4143
#define IDS_COL_PLACE                   4150
#define IDS_COL_POINTS                  4151
#define IDS_COL_PRIORITY                4152
#define IDS_COL_PRIVATE                 4153
#define IDS_COL_PTS                     4154
#define IDS_COL_Q                       4160
#define IDS_COL_Q_D                     4161
#define IDS_COL_RECEIVED                4162
#define IDS_COL_REG_NAME                4163
#define IDS_COL_REMINDER                4164
#define IDS_COL_REMINDER_DATE           4165
#define IDS_COL_REMINDER_TIME           4166
#define IDS_COL_REQ_ATTENDEES           4167
#define IDS_COL_REQ_CLOSING             4168
#define IDS_COL_REQ_OPENING             4169
#define IDS_COL_REQ_POINTS              4170
#define IDS_COL_RESOURCES               4171
#define IDS_COL_ROLE                    4172
#define IDS_COL_RUNTYPE                 4173
#define IDS_COL_SCH_PRIORITY            4180
#define IDS_COL_SCORE                   4181
#define IDS_COL_SCT                     4182
#define IDS_COL_SENSITIVITY             4183
#define IDS_COL_SHOW_TIME_AS            4184
#define IDS_COL_SPEED                   4185
#define IDS_COL_START_DATE              4186
#define IDS_COL_START_TIME              4187
#define IDS_COL_STATUS                  4188
#define IDS_COL_SUBJECT                 4189
#define IDS_COL_SUBNAME                 4190
#define IDS_COL_TENTATIVE               4191
#define IDS_COL_TIME                    4192
#define IDS_COL_TITLE                   4193
#define IDS_COL_TITLE_PTS               4194
#define IDS_COL_TITLES                  4195
#define IDS_COL_TOTAL_FAULTS            4196
#define IDS_COL_TOTAL_WORK              4197
#define IDS_COL_TRIAL                   4198
#define IDS_COL_TRIAL_EXISTPTS          4199
#define IDS_COL_TRIALNOTES              4200
#define IDS_COL_TYPE                    4201
#define IDS_COL_URL                     4202
#define IDS_COL_VENUE                   4210
#define IDS_COL_VENUES                  4211
#define IDS_COL_YARDS                   4220
#define IDS_COL_YPS                     4221
#define IDS_COL_OTHERPOINTS             4222
#define IDS_COL_DIV_LVL_EVT             4223
#define IDS_COL_OPEN_CLOSE              4224
#define IDS_COL_NAME_BREED_NOTE         4225
#define IDS_DATEFORMAT_DASH_MDY         4280
#define IDS_DATEFORMAT_SLASH_MDY        4281
#define IDS_DATEFORMAT_DASH_YMD         4282
#define IDS_DATEFORMAT_SLASH_YMD        4283
#define IDS_DATEFORMAT_DASH_DMY         4284
#define IDS_DATEFORMAT_SLASH_DMY        4285
#define IDS_DATEFORMAT_DASH_MMDDYYYY    4286
#define IDS_DATEFORMAT_SLASH_MMDDYYYY   4287
#define IDS_DATEFORMAT_DASH_YYYYMMDD    4288
#define IDS_DATEFORMAT_SLASH_YYYYMMDD   4289
#define IDS_DATEFORMAT_DASH_DDMMYYYY    4290
#define IDS_DATEFORMAT_SLASH_DDMMYYYY   4291
#define IDS_SYSERR_MEMORY               4300
#define IDS_SYSERR_SE_ERR_PNF           4301
#define IDS_SYSERR_SE_ERR_FNF           4302
#define IDS_SYSERR_ERROR_BAD_FORMAT     4303
#define IDS_SYSERR_SE_ERR_ACCESSDENIED  4304
#define IDS_SYSERR_SE_ERR_ASSOCINCOMPLETE 4305
#define IDS_SYSERR_SE_ERR_DDEBUSY       4306
#define IDS_SYSERR_SE_ERR_DDEFAIL       4307
#define IDS_SYSERR_SE_ERR_DDETIMEOUT    4308
#define IDS_SYSERR_SE_ERR_DLLNOTFOUND   4309
#define IDS_SYSERR_SE_ERR_NOASSOC       4310
#define IDS_SYSERR_SE_ERR_OOM           4311
#define IDS_SYSERR_SE_ERR_SHARE         4312
#define IDS_SYSERR_UNKNOWN              4313
#define IDS_ERR_COM_FAILED              4330
#define IDS_ERR_COMCTRL                 4331
#define IDS_ERR_RICHED32                4332
#define IDS_HTTP_ACCESS_DENIED          4350
#define IDS_HTTP_INVALID_HEADER_QUERY   4351
#define IDS_HTTP_URL_REDIRECTION        4352
#define IDS_HTTP_INVALID_URL            4353
#define IDS_HTTP_INVALID_URL_ERR        4354
#define IDS_HTTP_INVALID_URL2           4355
#define IDS_ERR_PARSING_DATA            4370
#define IDS_USE_PLUGIN                  4371
#define IDS_FILEEXT_DEF_ARB             4400
#define IDS_FILEEXT_FNAME_ARB           4401
#define IDS_FILEEXT_FILTER_ARB          4402
#define IDS_FILEEXT_DEF_DTD             4403
#define IDS_FILEEXT_FNAME_DTD           4404
#define IDS_FILEEXT_FILTER_DTD          4405
#define IDS_FILEEXT_DEF_XML             4406
#define IDS_FILEEXT_FNAME_XML           4407
#define IDS_FILEEXT_FILTER_XML          4408
#define IDS_FILEEXT_DEF_VCS             4409
#define IDS_FILEEXT_FNAME_VCS           4410
#define IDS_FILEEXT_FILTER_VCS          4411
#define IDS_FILEEXT_DEF_ICS             4412
#define IDS_FILEEXT_FNAME_ICS           4413
#define IDS_FILEEXT_FILTER_ICS          4414
#define IDS_FILEEXT_FILTER_ALL          4415
#define IDS_FILEEXT_FILTER_BMP          4416
#define IDS_FILEEXT_FILTER_TXTCSV       4417
#define IDS_FILEEXT_FILTER_MSEXCEL      4418
#define IDS_FILEEXT_FILTER_OOCALC       4419
#define IDS_ABOUT_TEXT                  4500
#define IDS_ABOUT_LINK_YAHOO            4501
#define IDS_ABOUT_LINK_EMAILHELP        4502
#define IDS_ABOUT_LINK_ARB              4503
#define IDS_ABOUT_LINK_ARB_DOWNLOAD     4504
#define IDS_UPDATED_CONFIG              4510
#define IDS_INTERNET_EXCEPTION          4511
#define IDS_ABOUT_VERSION               4512
#define IDS_HELP_UPDATE                 4513
#define IDS_UPDATE_CURRENT              4514
#define IDS_UPDATE_UNKNOWN              4515
#define IDS_VERSION_AVAILABLE           4516
#define IDS_CONFIG_NO_UPDATE            4517
#define IDS_ASSCOL_RUNS_FAULTS_TIME     4600
#define IDS_ASSCOL_RUNS_FAULTS_TIME_DESC 4601
#define IDS_ASSCOL_RUNS_TIME_FAULTS     4602
#define IDS_ASSCOL_RUNS_TIME_FAULTS_DESC 4603
#define IDS_ASSCOL_RUNS_OPEN_CLOSE      4604
#define IDS_ASSCOL_RUNS_OPEN_CLOSE_DESC 4605
#define IDS_ASSCOL_RUNS_POINTS          4606
#define IDS_ASSCOL_RUNS_POINTS_DESC     4607
#define IDS_ASSCOL_CALENDAR             4608
#define IDS_ASSCOL_CALENDAR_DESC        4609
#define IDS_ASSCOL_TRAINING             4610
#define IDS_ASSCOL_TRAINING_DESC        4611
#define IDS_ASSCOL_VIEW_TREE_DOG        4612
#define IDS_ASSCOL_VIEW_TREE_DOG_DESC   4613
#define IDS_ASSCOL_VIEW_TREE_TRIAL      4614
#define IDS_ASSCOL_VIEW_TREE_TRIAL_DESC 4615
#define IDS_ASSCOL_VIEW_TREE_RUN        4616
#define IDS_ASSCOL_VIEW_TREE_RUN_DESC   4617
#define IDS_ASSCOL_VIEW_RUNS_LIST       4618
#define IDS_ASSCOL_VIEW_RUNS_LIST_DESC  4619
#define IDS_ASSCOL_VIEW_CALENDAR_LIST   4620
#define IDS_ASSCOL_VIEW_CALENDAR_LIST_DESC 4621
#define IDS_ASSCOL_VIEW_TRAINING_LIST   4622
#define IDS_ASSCOL_VIEW_TRAINING_LIST_DESC 4623
#define IDS_ASSCOL_CALENDAR_APPT        4624
#define IDS_ASSCOL_CALENDAR_APPT_DESC   4625
#define IDS_ASSCOL_CALENDAR_TASK        4626
#define IDS_ASSCOL_CALENDAR_TASK_DESC   4627
#define IDS_ASSCOL_VIEW_CALENDAR        4628
#define IDS_ASSCOL_VIEW_CALENDAR_DESC   4629
#define IDS_WIZ_IMPORT_RUNS             4700
#define IDS_WIZ_IMPORT_RUNS_EXCEL       4701
#define IDS_WIZ_IMPORT_RUNS_CALC        4702
#define IDS_WIZ_IMPORT_RUNS_SPREAD      4703
#define IDS_WIZ_IMPORT_RUNS_PLUS        4704
#define IDS_WIZ_IMPORT_RUNS_ARB         4705
#define IDS_WIZ_EXPORT_RUNS             4706
#define IDS_WIZ_EXPORT_RUNS_EXCEL       4707
#define IDS_WIZ_EXPORT_RUNS_CALC        4708
#define IDS_WIZ_EXPORT_RUNS_SPREAD      4709
#define IDS_WIZ_IMPORT_CAL              4710
#define IDS_WIZ_IMPORT_CAL_EXCEL        4711
#define IDS_WIZ_IMPORT_CAL_CALC         4712
#define IDS_WIZ_IMPORT_CAL_SPREAD       4713
#define IDS_WIZ_IMPORT_CAL_ARB          4714
#define IDS_WIZ_EXPORT_CAL              4715
#define IDS_WIZ_EXPORT_CAL_EXCEL        4716
#define IDS_WIZ_EXPORT_CAL_CALC         4717
#define IDS_WIZ_EXPORT_CAL_SPREAD       4718
#define IDS_WIZ_EXPORT_CAL_ARB          4719
#define IDS_WIZ_EXPORT_CAL_VCAL         4720
#define IDS_WIZ_EXPORT_CAL_VCAL_SPREAD  4721
#define IDS_WIZ_EXPORT_CAL_ICAL         4722
#define IDS_WIZ_EXPORT_CAL_ICAL_SPREAD  4723
#define IDS_WIZ_EXPORT_CAL_APPT         4724
#define IDS_WIZ_EXPORT_CAL_APPT_EXCEL   4725
#define IDS_WIZ_EXPORT_CAL_APPT_SPREAD  4726
#define IDS_WIZ_EXPORT_CAL_TASK         4727
#define IDS_WIZ_EXPORT_CAL_TASK_EXCEL   4728
#define IDS_WIZ_EXPORT_CAL_TASK_SPREAD  4729
#define IDS_WIZ_IMPORT_LOG              4730
#define IDS_WIZ_IMPORT_LOG_EXCEL        4731
#define IDS_WIZ_IMPORT_LOG_CALC         4732
#define IDS_WIZ_IMPORT_LOG_SPREAD       4733
#define IDS_WIZ_IMPORT_LOG_ARB          4734
#define IDS_WIZ_EXPORT_LOG              4735
#define IDS_WIZ_EXPORT_LOG_EXCEL        4736
#define IDS_WIZ_EXPORT_LOG_CALC         4737
#define IDS_WIZ_EXPORT_LOG_SPREAD       4738
#define IDS_WIZ_EXPORT_LOG_ARB          4739
#define IDS_WIZ_IMPORT_CONFIG           4740
#define IDS_WIZ_IMPORT_CONFIG_ARB       4741
#define IDS_WIZ_EXPORT_CONFIG           4742
#define IDS_WIZ_EXPORT_CONFIG_ARB       4743
#define IDS_WIZ_EXPORT_DTD              4744
#define IDS_WIZ_EXPORT_DTD_ARB          4745
#define IDS_WIZ_EXPORT_XML              4746
#define IDS_WIZ_EXPORT_XML_ARB          4747
#define IDS_RUNS                        5000
#define IDS_POINTS                      5001
#define IDS_CALENDAR                    5002
#define IDS_TRAINING                    5003
#define IDS_ADDED                       5010
#define IDS_ALL                         5011
#define IDS_BLANK_COLUMN                5012
#define IDS_BUTTONS_DIVISIONS           5013
#define IDS_BUTTONS_EVENTS              5014
#define IDS_BUTTONS_LEVELS              5016
#define IDS_BUTTONS_MULTIQS             5017
#define IDS_BUTTONS_TITLES              5019
#define IDS_CHANGED                     5021
#define IDS_CRCD_BTN_CLEARCOURSE        5024
#define IDS_CRCD_BTN_INSERTCOURSE       5025
#define IDS_CRCD_BTN_VIEWIMAGE          5026
#define IDS_CRCD_BTN_VIEWTEXT           5027
#define IDS_DELETED                     5028
#define IDS_DIVISION_NAME               5029
#define IDS_EXISTING_POINTS             5033
#define IDS_FAULT_TYPE_NAME             5034
#define IDS_FAULT_TYPES                 5035
#define IDS_INDICATOR_BLANK             5036
#define IDS_INFO_CLUB                   5037
#define IDS_INFO_JUDGE                  5038
#define IDS_INFO_LOCATION               5039
#define IDS_INVALID_NAME                5040
#define IDS_LEVEL_NAME                  5041
#define IDS_LIFETIME_POINTS             5043
#define IDS_OTHERPOINTS                 5045
#define IDS_OTHERPTS_ALL                5047
#define IDS_OTHERPTS_EVENT              5048
#define IDS_OTHERPTS_EVENT_LEVEL        5049
#define IDS_OTHERPTS_LEVEL              5050
#define IDS_PARTNERS                    5051
#define IDS_PLACEMENT_POINTS            5052
#define IDS_Q                           5054
#define IDS_RUN_PROPERTIES              5055
#define IDS_SCORING_REQUIRED_POINTS     5057
#define IDS_SEARCH_NOTES                5058
#define IDS_SPEEDPTS                    5059
#define IDS_SQ                          5060
#define IDS_SUBLEVEL_NAME               5061
#define IDS_TITLEPOINT_LIFETIME         5063
#define IDS_TITLEPOINT_NORMAL           5064
#define IDS_TITLEPOINT_PLACEMENT        5065
#define IDS_TITLES                      5066
#define IDS_TITLING_POINTS              5067
#define IDS_TOTAL                       5068
#define IDS_UNEARNED                    5069
#define IDS_UPDATED                     5070
#define IDS_VIEWING_OPTIONS             5072
#define IDS_EXPORTING                   5073
#define IDS_AFFECTED_RUNS               5100
#define IDS_ARE_YOU_SURE_CONTINUE       5102
#define IDS_AUTODELETE_CAL              5103
#define IDS_BAD_EVENT                   5104
#define IDS_BAD_SCORINGMETHOD           5105
#define IDS_BLANK_CALLNAME              5106
#define IDS_CHANGEDIV_ISSUES            5107
#define IDS_CHANGELEVEL_ISSUES          5108
#define IDS_CHANGESUBLEVEL_ISSUES       5109
#define IDS_CONFIG_CHECK_VALUE          5110
#define IDS_CONFIG_PLACE_TOOSMALL       5111
#define IDS_CONFIG_PLACE_UNIQUE         5112
#define IDS_CONFIGEVENT_BONUS           5113
#define IDS_CONFIGEVENT_CLEANQ          5114
#define IDS_CONFIGEVENT_DATEORDER       5115
#define IDS_CONFIGEVENT_DROPFRAC        5116
#define IDS_CONFIGEVENT_OVERLAPDATES    5117
#define IDS_CONFIGEVENT_PLACEMENT0      5118
#define IDS_CONFIGEVENT_REQCLOSE        5119
#define IDS_CONFIGEVENT_REQOPEN         5120
#define IDS_CONFIGEVENT_SPEEDPTS        5121
#define IDS_CONFIGEVENT_STYLE           5122
#define IDS_CONFIGEVENT_SUPERQ          5123
#define IDS_CONFIGEVENT_TF_FROMSCORE    5124
#define IDS_CONFIGEVENT_TF_OVER         5125
#define IDS_CONFIGEVENT_TF_UNDER        5126
#define IDS_CONFIGEVENT_TIMEFAULTMULT   5127
#define IDS_COPYOF                      5128
#define IDS_CREATE_LEVEL                5129
#define IDS_CREATEDOG_FAILED            5130
#define IDS_CREATERUN_FAILED            5131
#define IDS_CREATERUN_FILTERED          5132
#define IDS_CREATETRIAL_FAILED          5133
#define IDS_CREATETRIAL_FILTERED        5134
#define IDS_DELETE_DOG_DATA             5137
#define IDS_DELETE_EVENT_DATA           5138
#define IDS_DELETE_TRIAL_DATA           5139
#define IDS_ENTER_NAME                  5140
#define IDS_ENTER_SHORTNAME             5141
#define IDS_INTERNAL_ERROR              5142
#define IDS_MIN_RESOLUTION              5143
#define IDS_NAME_FILTER                 5144
#define IDS_NAME_IN_USE                 5145
#define IDS_NAME_IN_USE_MERGE           5146
#define IDS_NEED_CLUB                   5147
#define IDS_NEW_DOG                     5148
#define IDS_NO_LINKED_FILES             5149
#define IDS_NONFATAL_MSGS               5151
#define IDS_SELECT_DIVISION             5152
#define IDS_SELECT_EVENT                5153
#define IDS_SELECT_JUDGE                5154
#define IDS_SELECT_LEVEL                5155
#define IDS_SELECT_Q                    5156
#define IDS_SELECT_STYLE                5157
#define IDS_TITLEPTS_EXISTS             5158
#define IDS_UNABLE_TO_OPEN              5161
#define IDS_BAD_VERSION                 5162
#define IDS_NO_DELIM_SPECIFIED          5163
#define IDS_SPECIFY_DATEFORMAT          5164
#define IDS_ERRORS_DURING_EXPORT        5165
#define IDS_EXPORT_FAILED               5166
#define IDS_IMPORT_FAILED               5167
#define IDS_BAD_DRAWDATE                5168
#define IDS_UPDATED_CAL_ITEMS           5200
#define IDS_ADDED_CLUBS                 5201
#define IDS_ADDED_DOGS                  5202
#define IDS_ADDED_EXISTINGPTS           5203
#define IDS_ADDED_JUDGES                5204
#define IDS_ADDED_LOCATIONS             5205
#define IDS_ADDED_REGNUMS               5206
#define IDS_ADDED_TITLES                5207
#define IDS_ADDED_TRAINING_ITEMS        5208
#define IDS_ADDED_TRIALS                5209
#define IDS_CANNOT_FIND                 5210
#define IDS_CANNOT_OPEN                 5211
#define IDS_CONFIG_DELETE_RUNS          5212
#define IDS_FILE_PREVIEW                5217
#define IDS_LOAD_FAILED                 5218
#define IDS_NOT_VISIBLE                 5219
#define IDS_NUM_EVENTS                  5220
#define IDS_NUM_RUNS_QS                 5221
#define IDS_NUM_TRAINING                5222
#define IDS_POINTS_CLEAN                5223
#define IDS_POINTS_JUDGES               5224
#define IDS_POINTS_PARTNERS             5225
#define IDS_POINTS_QS                   5226
#define IDS_POINTS_RUNS_JUDGES          5227
#define IDS_POINTS_SPEED                5228
#define IDS_POINTS_SPEED_SUBTOTAL       5229
#define IDS_POINTS_SQS                  5230
#define IDS_READING_ROWS                5231
#define IDS_READING_ROWSCOLS            5232
#define IDS_TRIAL_DATES                 5234
#define IDS_VENUE_CONFIG_MISSING        5235
#define IDS_YEARS                       5236
#define IDS_IMPORT_SKIP_NOCONFIG        5237
#define IDS_IMPORT_BAD_DATE_RUN         5238
#define IDS_IMPORT_BAD_VENUE            5239
#define IDS_IMPORT_BAD_DATE_CALSTART    5240
#define IDS_IMPORT_BAD_DATE_CALEND      5241
#define IDS_IMPORT_BAD_DATE_CALOPEN     5242
#define IDS_IMPORT_BAD_DATE_CALCLOSE    5243
#define IDS_IMPORT_BAD_CAL_VALUE        5244
#define IDS_IMPORT_BAD_DATE_LOG         5245
#define IDS_IMPORT_STATS                5246
#define ID_FILE_EXPORT_WIZARD           32772
#define ID_FILE_LINKED                  32774
#define ID_FILE_PRINT_BLANK_RUNS        32775
#define ID_FILE_CHOOSELANGUAGE          32776
#define ID_EDIT_FIND_NEXT               32780
#define ID_EDIT_FIND_PREVIOUS           32781
#define ID_EDIT_CONFIGURATION           32782
#define ID_EDIT_DUPLICATE               32784
#define ID_AGILITY_NEW_DOG              32790
#define ID_AGILITY_EDIT_DOG             32791
#define ID_AGILITY_DELETE_DOG           32792
#define ID_AGILITY_NEW_TITLE            32800
#define ID_AGILITY_EDIT_TITLE           32801
#define ID_AGILITY_DELETE_TITLE         32802
#define ID_AGILITY_NEW_TRIAL            32810
#define ID_AGILITY_EDIT_TRIAL           32811
#define ID_AGILITY_DELETE_TRIAL         32812
#define ID_AGILITY_NEW_RUN              32820
#define ID_AGILITY_EDIT_RUN             32821
#define ID_AGILITY_DELETE_RUN           32822
#define ID_AGILITY_NEW_CALENDAR         32830
#define ID_AGILITY_EDIT_CALENDAR        32831
#define ID_AGILITY_DELETE_CALENDAR      32832
#define ID_AGILITY_UPDATE_CALENDAR      32833
#define ID_AGILITY_EXPORT_CALENDAR      32834
#define ID_AGILITY_CREATEENTRY_CALENDAR 32835
#define ID_AGILITY_NEW_TRAINING         32840
#define ID_AGILITY_EDIT_TRAINING        32841
#define ID_AGILITY_DELETE_TRAINING      32842
#define ID_NOTES_CLUBS                  32850
#define ID_NOTES_JUDGES                 32851
#define ID_NOTES_LOCATIONS              32852
#define ID_NOTES_SEARCH                 32853
#define ID_AGILITY_PRINT_TRIAL          32854
#define ID_AGILITY_PRINT_RUNS           32855
#define ID_VIEW_OPTIONS                 32860
#define ID_VIEW_CUSTOMIZE               32861
#define ID_VIEW_SORTRUNS                32862
#define ID_VIEW_RUNS_BY_TRIAL           32863
#define ID_VIEW_HIDDEN                  32864
#define ID_VIEW_TABLE_IN_YPS            32865
#define ID_VIEW_POINTS_VIEW_SORT        32866
#define ID_HELP_CONTENTS                32870
#define ID_HELP_UPDATE                  32871
#define ID_HELP_SPLASH                  32872
#define ID_HELP_SYSINFO                 32873
#define ID_NEXT_TAB                     32880
#define ID_PREV_TAB                     32881
#define ID_REORDER                      32890
#define ID_EXPAND                       32891
#define ID_COLLAPSE                     32892
#define ID_EXPAND_ALL                   32893
#define ID_COLLAPSE_ALL                 32894
#define ID_DETAILS                      32895
#define ID_COPY_TITLES_LIST             32896
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_FILTERED           59143
#define ID_INDICATOR_DOG                59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32900
#define _APS_NEXT_CONTROL_VALUE         1680
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
