//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AgilityBook.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DTD_AGILITYRECORDBOOK       129
#define IDR_XML_DEFAULT_CONFIG          130
#define IDR_CONFIGURE                   131
#define IDR_DOG                         132
#define IDR_TRIAL                       133
#define IDR_RUN                         134
#define IDR_RUNS                        135
#define IDR_CALENDAR                    136
#define IDI_AGILITYBOOKDOC              140
#define IDI_CALENDAR_EMPTY              141
#define IDI_CALENDAR_TENTATIVE          142
#define IDI_CALENDAR_PLAN               143
#define IDI_CALENDAR_PLAN_TENTATIVE     144
#define IDI_CALENDAR_ENTERED            145
#define IDI_CALENDAR_ENTERED_TENTATIVE  146
#define IDI_CHECKED                     147
#define IDI_UNCHECKED                   148
#define IDD_NAME                        150
#define IDD_NAME_DESC                   151
#define IDD_CONFIGURE                   152
#define IDD_CALENDAR                    153
#define IDD_CONFIG_OTHERPOINTS          154
#define IDD_CONFIG_EVENT                155
#define IDD_DOG_PICKER                  156
#define IDD_DOG                         157
#define IDD_TITLE                       158
#define IDD_REG_NUM                     159
#define IDD_TRIAL                       160
#define IDD_CLUB                        161
#define IDD_RUN_SCORE                   162
#define IDD_RUN_COMMENTS                163
#define IDD_RUN_REFERENCE               164
#define IDD_RUN_CRCD                    165
#define IDD_REF_RUN                     166
#define IDD_PARTNER                     167
#define IDD_OTHER_POINT                 168
#define IDD_LISTCTRL                    169
#define IDD_FAULT                       170
#define IDD_VIEW_OPTIONS_CALENDAR       171
#define IDD_VIEW_OPTIONS_FILTER         172
#define IDD_VIEW_OPTIONS_FONTS          173
#define IDD_REORDER                     174
#define IDD_CONFIG_UPDATE               175
#define IDD_TITLE_POINTS                176
#define IDD_MESSAGE                     177
#define IDC_ABOUT_TEXT                  1000
#define IDC_ABOUT_LINK1                 1001
#define IDC_ABOUT_LINK2                 1002
#define IDC_ABOUT_LINK3                 1003
#define IDC_VENUES                      1004
#define IDC_NAME                        1005
#define IDC_TALLY                       1006
#define IDC_DESC                        1007
#define IDC_PARTNER                     1008
#define IDC_METHODS                     1009
#define IDC_UNUSED                      1010
#define IDC_DIVISION                    1011
#define IDC_LEVEL                       1012
#define IDC_TYPE                        1013
#define IDC_SUPERQ                      1014
#define IDC_MACH                        1015
#define IDC_DOUBLEQ                     1016
#define IDC_NEW                         1017
#define IDC_DELETE                      1018
#define IDC_EVENT                       1019
#define IDC_CALLNAME                    1020
#define IDC_DOB                         1021
#define IDC_BREED                       1022
#define IDC_AGE_TEXT                    1023
#define IDC_REG_NAME                    1024
#define IDC_TITLE_NEW                   1025
#define IDC_TITLE_EDIT                  1026
#define IDC_TITLE_DELETE                1027
#define IDC_TITLES                      1028
#define IDC_REG_NEW                     1029
#define IDC_REG_EDIT                    1030
#define IDC_REG_DELETE                  1031
#define IDC_REG_NUMS                    1032
#define IDC_NOTES                       1033
#define IDC_DATE                        1034
#define IDC_DECEASED                    1034
#define IDC_REG_NUM                     1035
#define IDC_LOCATION                    1036
#define IDC_CLUB_NEW                    1037
#define IDC_CLUB_DELETE                 1038
#define IDC_CLUBS                       1039
#define IDC_VENUE                       1040
#define IDC_CLUB_EDIT                   1041
#define IDC_CLUB                        1042
#define IDC_HEIGHT                      1043
#define IDC_JUDGE                       1044
#define IDC_PARTNERS_EDIT               1045
#define IDC_CONDITIONS                  1046
#define IDC_FAULTS_TEXT                 1047
#define IDC_FAULTS                      1048
#define IDC_TIME4FAULT_TEXT             1049
#define IDC_TIME4FAULT                  1050
#define IDC_YARDS_TEXT                  1051
#define IDC_YARDS                       1052
#define IDC_YPS_TEXT                    1053
#define IDC_YPS                         1054
#define IDC_SCT_TEXT                    1055
#define IDC_SCT                         1056
#define IDC_TOTAL_FAULTS_TEXT           1057
#define IDC_TOTAL_FAULTS                1058
#define IDC_OPENING_PTS_TEXT            1059
#define IDC_OPENING_PTS                 1060
#define IDC_CLOSING_PTS_TEXT            1061
#define IDC_CLOSING_PTS                 1062
#define IDC_TIME4SCORE_TEXT             1063
#define IDC_TIME4SCORE                  1064
#define IDC_OPEN_PTS_TEXT               1065
#define IDC_OPEN_PTS                    1066
#define IDC_CLOSE_PTS_TEXT              1067
#define IDC_CLOSE_PTS                   1068
#define IDC_PLACE                       1069
#define IDC_IN_CLASS                    1070
#define IDC_DOGS_QD                     1071
#define IDC_Q                           1072
#define IDC_SCORE                       1073
#define IDC_TITLE_POINTS_TEXT           1074
#define IDC_TITLE_POINTS                1075
#define IDC_MACHPTS_TEXT                1076
#define IDC_MACHPTS                     1077
#define IDC_DOUBLE_Q                    1078
#define IDC_COMMENTS_FAULTS             1079
#define IDC_FAULTS_LIST                 1080
#define IDC_COMMENTS                    1081
#define IDC_REF_RUNS                    1082
#define IDC_EDIT                        1083
#define IDC_OTHERPOINTS                 1084
#define IDC_DATE_START                  1085
#define IDC_DATE_END                    1086
#define IDC_TENTATIVE                   1087
#define IDC_ENTER_NOT                   1088
#define IDC_ENTER_PLANNING              1089
#define IDC_ENTER_ENTERED               1090
#define IDC_DATE_OPENS                  1091
#define IDC_DATE_OPENS_UNKNOWN          1092
#define IDC_DATE_CLOSES                 1093
#define IDC_DATE_CLOSES_UNKNOWN         1094
#define IDC_POINTS                      1095
#define IDC_TIME                        1096
#define IDC_HANDLER                     1097
#define IDC_CRCD                        1098
#define IDC_LIST                        1099
#define IDC_AUTO_DELETE                 1100
#define IDC_HIDE_OLD                    1101
#define IDC_OLD_ENTRY_DAYS              1102
#define IDC_HIDE_OVERLAP                1103
#define IDC_DAY_OF_WEEK                 1104
#define IDC_SIZE_X                      1105
#define IDC_SIZE_Y                      1106
#define IDC_OPTIONS_DATES_ALL           1107
#define IDC_OPTIONS_DATES_RANGE         1108
#define IDC_OPTIONS_DATE_START_CHECK    1109
#define IDC_OPTIONS_DATE_END_CHECK      1110
#define IDC_OPTIONS_DATE_START          1111
#define IDC_OPTIONS_DATE_END            1112
#define IDC_OPTIONS_VENUES_ALL          1113
#define IDC_OPTIONS_VENUES_SELECTED     1114
#define IDC_OPTIONS_VENUES              1115
#define IDC_OPTIONS_RUNS_ALL            1116
#define IDC_OPTIONS_RUNS_Q              1117
#define IDC_OPTIONS_RUNS_NON_Q          1118
#define IDC_FONT_GENERAL_PRINT          1130
#define IDC_FONT_GENERAL_PRINT_TEXT     1131
#define IDC_FONT_CAL_VIEW_DATE          1132
#define IDC_FONT_CAL_VIEW_DATE_TEXT     1133
#define IDC_FONT_CAL_VIEW_TEXT          1134
#define IDC_FONT_CAL_VIEW_TEXT_TEXT     1135
#define IDC_FONT_CAL_PRINT_DATE         1136
#define IDC_FONT_CAL_PRINT_DATE_TEXT    1137
#define IDC_FONT_CAL_PRINT_TEXT         1138
#define IDC_FONT_CAL_PRINT_TEXT_TEXT    1139
#define IDC_RECEIVED                    1140
#define IDC_TRIAL                       1141
#define IDC_MOVE_UP                     1142
#define IDC_MOVE_DOWN                   1143
#define IDC_UPDATE                      1144
#define IDC_UPDATE_DEFAULT              1145
#define IDC_UPDATE_EXISTING             1146
#define IDC_FILENAME                    1147
#define IDC_DROP_FRACTIONS              1148
#define IDC_VERIFIED                    1149
#define IDC_IS_DECEASED                 1150
#define IDS_RUNS                        5000
#define IDS_POINTS                      5001
#define IDS_CALENDAR                    5002
#define IDS_PARTNERS                    5003
#define IDS_VENUES                      5004
#define IDS_VENUE_NAME                  5005
#define IDS_FAULT_TYPES                 5006
#define IDS_FAULT_TYPE_NAME             5007
#define IDS_OTHERPOINTS                 5008
#define IDS_OTHERPOINTS_NAME            5009
#define IDS_DIVISIONS                   5010
#define IDS_DIVISION_NAME               5011
#define IDS_TITLES                      5012
#define IDS_TITLE_NAME                  5013
#define IDS_LEVELS                      5014
#define IDS_LEVEL_NAME                  5015
#define IDS_SUBLEVEL_NAME               5016
#define IDS_EVENTS                      5017
#define IDS_EVENT_NAME                  5018
#define IDS_SCORING                     5019
#define IDS_Q                           5020
#define IDS_SQ                          5021
#define IDS_SUPER_Q                     5022
#define IDS_QQ                          5023
#define IDS_DOUBLE_Q                    5024
#define IDS_MACHPTS                     5025
#define IDS_COL_BREED                   5030
#define IDS_COL_CLOSES                  5031
#define IDS_COL_CLUB                    5032
#define IDS_COL_DATE                    5033
#define IDS_COL_DIVISION                5034
#define IDS_COL_DOG                     5035
#define IDS_COL_END_DATE                5036
#define IDS_COL_EVENT                   5037
#define IDS_COL_FAULT                   5038
#define IDS_COL_HANDLER                 5039
#define IDS_COL_IN_CLASS                5040
#define IDS_COL_JUDGE                   5041
#define IDS_COL_LEVEL                   5042
#define IDS_COL_LOCATION                5043
#define IDS_COL_NAME                    5044
#define IDS_COL_NOTE                    5045
#define IDS_COL_NOTES                   5046
#define IDS_COL_NUMBER                  5047
#define IDS_COL_OPENS                   5048
#define IDS_COL_PLACE                   5049
#define IDS_COL_POINTS                  5050
#define IDS_COL_PTS                     5051
#define IDS_COL_Q                       5052
#define IDS_COL_Q_D                     5053
#define IDS_COL_RECEIVED                5054
#define IDS_COL_SCORE                   5055
#define IDS_COL_START_DATE              5056
#define IDS_COL_TIME                    5057
#define IDS_COL_VENUE                   5058
#define IDS_COL_HEIGHT                  5059
#define IDS_ABOUT_TEXT                  5070
#define IDS_ABOUT_LINK1                 5071
#define IDS_ABOUT_LINK2                 5072
#define IDS_ABOUT_LINK3                 5073
#define IDS_NEW                         5081
#define IDS_CONFIGURE                   5082
#define IDS_SCORING_NAME                5083
#define IDS_DELETE_VENUE                5084
#define IDS_DELETE_OTHERPOINTS          5085
#define IDS_DELETE_DIVISION             5086
#define IDS_DELETE_LEVEL                5087
#define IDS_DELETE_TITLE                5088
#define IDS_DELETE_EVENT                5089
#define IDS_DELETE_ALL                  5090
#define IDS_DELETE_ALL_OTHERPOINTS      5091
#define IDS_DELETE_ALL_TITLES           5092
#define IDS_NAME_IN_USE                 5093
#define IDS_ALL                         5094
#define IDS_TITLEPTS_EXISTS             5095
#define IDS_MIN_RESOLUTION              5096
#define IDS_CANNOT_OPEN                 5097
#define IDS_VIEWING_OPTIONS             5098
#define IDS_RUN_PROPERTIES              5099
#define IDS_CONFIG_DELETE_RUNS          5100
#define IDS_SELECT_DIVISION             5101
#define IDS_SELECT_LEVEL                5102
#define IDS_SELECT_EVENT                5103
#define IDS_SELECT_HEIGHT               5104
#define IDS_SELECT_JUDGE                5105
#define IDS_SELECT_Q                    5106
#define IDS_BAD_EVENT                   5107
#define IDS_BAD_SCORINGMETHOD           5108
#define IDS_SCORING_REQUIRED_POINTS     5109
#define IDS_SCORING_POINTS              5110
#define IDS_NUM_EVENTS                  5111
#define IDS_NUM_RUNS_QS                 5112
#define IDS_AUTODELETE_CAL              5113
#define IDS_CREATETRIAL_FAILED          5114
#define IDS_NEED_CLUB                   5115
#define IDS_VENUE_CONFIG_MISSING        5116
#define IDS_DELETE_DOG_DATA             5117
#define IDS_DELETE_TRIAL_DATA           5118
#define IDS_DELETE_EVENT_DATA           5119
#define IDS_COPYOF                      5120
#define IDS_CHANGEDIV_ISSUES            5121
#define IDS_CHANGELEVEL_ISSUES          5122
#define IDS_CHANGESUBLEVEL_ISSUES       5123
#define IDS_NOCONFIGDATA_FOUND          5124
#define IDS_UNKNOWN_DOCUMENT_VERSION    5125
#define IDS_OTHERPTS_ALL                5126
#define IDS_OTHERPTS_EVENT              5127
#define IDS_OTHERPTS_LEVEL              5128
#define IDS_OTHERPTS_EVENT_LEVEL        5129
#define IDS_CONFIG_NO_UPDATE            5130
#define IDS_XERCES_ERROR                5131
#define IDS_POINTS_RUNS_JUDGES          5132
#define IDS_POINTS_PARTNERS             5133
#define IDS_POINTS_QS                   5134
#define IDS_POINTS_CLEAN                5135
#define IDS_POINTS_JUDGES               5136
#define IDS_POINTS_SQS                  5137
#define IDS_POINTS_MACH_SUBTOTAL        5138
#define IDS_POINTS_QQS                  5139
#define IDS_POINTS_MACH                 5140
#define IDS_CONFIG_TITLEPTS             5141
#define IDS_FILEEXT_DEF_ARB             5142
#define IDS_FILEEXT_FNAME_ARB           5143
#define IDS_FILEEXT_FILTER_ARB          5144
#define IDS_CREATERUN_FAILED            5145
#define IDS_CREATETRIAL_FILTERED        5146
#define IDS_CREATERUN_FILTERED          5147
#define ID_FILE_IMPORT_CONFIG           32772
#define ID_FILE_EXPORT                  32773
#define ID_EDIT_CONFIGURATION           32774
#define ID_CONFIG_ADD                   32775
#define ID_CONFIG_DUPLICATE             32776
#define ID_CONFIG_EDIT                  32777
#define ID_CONFIG_DELETE                32778
#define ID_AGILITY_NEW_CALENDAR         32779
#define ID_AGILITY_NEW_DOG              32780
#define ID_AGILITY_NEW_TITLE            32781
#define ID_AGILITY_NEW_TRIAL            32782
#define ID_AGILITY_NEW_RUN              32783
#define ID_AGILITY_EDIT_CALENDAR        32784
#define ID_AGILITY_EDIT_DOG             32785
#define ID_AGILITY_EDIT_TITLE           32786
#define ID_AGILITY_EDIT_TRIAL           32787
#define ID_AGILITY_EDIT_RUN             32788
#define ID_AGILITY_DELETE_CALENDAR      32789
#define ID_AGILITY_DELETE_DOG           32790
#define ID_AGILITY_DELETE_TITLE         32791
#define ID_AGILITY_DELETE_TRIAL         32792
#define ID_AGILITY_DELETE_RUN           32793
#define ID_VIEW_OPTIONS                 32794
#define ID_EXPAND                       32795
#define ID_EXPAND_ALL                   32796
#define ID_COLLAPSE                     32797
#define ID_COLLAPSE_ALL                 32798
#define ID_NEXT_TAB                     32799
#define ID_PREV_TAB                     32800
#define ID_AGILITY_CREATEENTRY_CALENDAR 32801
#define ID_REORDER                      32802
#define ID_VIEW_SORTRUNS                32803
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_FILTERED           59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1151
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
