os:
  - Windows Server 2012 R2

install:
  # Generate solution files using cmake, in 'builds' directory.
  # No need to create it because it's part of the repo.
  - cd builds && cmake -G "Visual Studio 12" ../ && cd ..

configuration:
  - Debug
  - Release

build:
  project: builds/UnitTest++.sln
