Document: agilitybook
Title: Debian agilitybook Manual
Author: <insert document author here>
Abstract: This manual describes what agilitybook is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/agilitybook/agilitybook.sgml.gz

Format: postscript
Files: /usr/share/doc/agilitybook/agilitybook.ps.gz

Format: text
Files: /usr/share/doc/agilitybook/agilitybook.text.gz

Format: HTML
Index: /usr/share/doc/agilitybook/html/index.html
Files: /usr/share/doc/agilitybook/html/*.html

  
